### PR TITLE
add image dithering filter #8598

### PR DESCRIPTION
**Pull request by diantanjung**
Fix this issue [#8598](https://github.com/gohugoio/hugo/issues/8598)

You can set the dither algorithm and palette colors to use with a 3 or 6 digit hex code starting with #. If you set palettes only one color, it will add Black and White automatically. Use png file for best result. List algorithm :
- FloydSteinberg (default)
- JarvisJudiceNinke
- Stucki
- Atkinson
- Burkes
- Sierra
- TwoRowSierra
- SierraLite

example :
`{{ $img = $img.Filter (images.Dither "Stucki #ffffff #8D1900") }}`
`{{ $img = $img.Filter (images.Dither "FloydSteinberg #ffffff #8D1900 #AD8359 #508A00 #1A6C82") }}`

### CODE REVIEW

**Comment by bep** [comment]
The code provide here are entirely written by you?

**Comment by diantanjung** [comment]
No, I modified from https://github.com/brouxco/dithering

**Comment by diantanjung** [comment]
hi @bep 
is there I need to improve the code?

**Comment by bep** [comment]
Thanks, but this was not wha I had in mind when I said that we should try to avoid adding a new dependency for this. It may be OK vs the upstream license, but it's not code that I want to maintain here.

I was originally thinking about using any existing dithering filter in Go's stdlib. Let's discuss this on the original issue.

**Pull request closed without merging**
