### PR TITLE
Try out Windows builds in Travis

### PR DESCRIPTION
**Pull request by emirb**
Trying out [early Windows release](https://blog.travis-ci.com/2018-10-11-windows-early-release)

### CODE REVIEW

**Comment by bep** [comment]
It would be cool if we could use Travis only, but with the extended build, our build setup is not trivial.

**Comment by moorereason** [comment]
Travis is working on the ["There is not enough space on the disk" issue](https://travis-ci.community/t/there-is-not-enough-space-on-the-disk/338).

**Comment by moorereason** [comment]
Windows builds on Travis are green ([except for tip](https://travis-ci.community/t/go-command-not-found/340))! :tada:

This is big.

**Comment by bep** [comment]
Yes, this is pretty great. The "Go tip" build is a way to get "early warnings" about API builds etc., so that is fine if we could turn it off. That said, we usually build for 2 Go versions, so we should think about how to set it up once Go 1.12 is out etc.

**Comment by bep** [comment]
@emirb what is the status of this? Is there a way to configure "the matrix" re. the discussion above?

**Comment by emirb** [comment]
@bep If I understood your intentions correctly, it is already set up like that.
Travis runs first matrix of tests with 1.11 and another with tip. Failures are allowed for tip, so we can get early warnings, however, they won't break the build.

**Comment by bep** [comment]
>@bep If I understood your intentions correctly, it is already set up like that.

My intentions are to get a setup where I can exclude a Go version for an OS. That failures on tip "is allowed" doesn't mean that we want to run it for every commit, that is a waste and confuses people who look at the build status.

**Comment by emirb** [comment]
@bep Got you; the latest commit does just that.

**Pull request merged**
