### PR TITLE
Publish tagged as Github Packages

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

https://github.com/gliptak/hugo/actions/runs/975239969

https://github.com/gliptak/hugo/pkgs/container/hugo

```
docker run ghcr.io/gliptak/hugo:latest version
hugo v0.85.0-DEV linux/amd64 BuildDate=2021-06-27T01:03:38Z
```

#5056

### CODE REVIEW

**Comment by gliptak** [comment]
@bep please approve running workflows

**Comment by bep** [comment]
@gliptak I'm not approving this until I understand what it does.

**Comment by gliptak** [comment]
@bep details were linked above

as per #5056, while there is a Dockerfile, an image isn't published for `hugo`

This Github Actions publishes tagged sources as Github Packages

Here is a publishing run on my fork:

https://github.com/gliptak/hugo/actions/runs/975239969

Here is the published artifact in my fork:

https://github.com/gliptak/hugo/pkgs/container/hugo

Here is a sample run for the artifact published on my fork:

```
docker run ghcr.io/gliptak/hugo:latest version
hugo v0.85.0-DEV linux/amd64 BuildDate=2021-06-27T01:03:38Z
```

**Comment by bep** [comment]
OK, thanks, but we're currently not going to do that. I look at the Dockerfile in this repo as a convenience thing. Once we publish it to some official repo we need to do a whole new level of QA, which I'm certainly not prepared to take on at the moment.

**Comment by gliptak** [comment]
@bep considering that testing already happens against `ubuntu` at https://github.com/gohugoio/hugo/blob/master/.github/workflows/test.yml#L11, the `Dockerfile` testing might be building it and getting a version number out running it. Let me know if you are interested in a PR updating `test.yml` with basic `Dockerfile` testing

**Pull request closed without merging**
