### PR TITLE
Create default link and image render hooks

### LINKED ISSUE #11933: Create default link and image render hooks
With the implementation of https://github.com/gohugoio/hugo/issues/11453 and https://github.com/gohugoio/hugo/issues/11904 we no longer duplicate page resources per language[^1]. This is applicable to multilingual, single-host sites. 

When resources are not duplicated per language (the default), link and image render hooks are required to properly resolve markdown destinations (links and image).

[^1]: This can be disabled by setting `markup.goldmark.duplicateResourceFiles = true` in site configuration.

Per [this discussion](https://github.com/gohugoio/hugo/issues/11904#issuecomment-1902270945), the site config would be:

```text
[markup.goldmark.renderhooks.image]
enable = true
multilingualOnly = true

[markup.goldmark.renderhooks.link]
enable = true
multilingualOnly = true
```

Candidate render hooks:

<details>
<summary>layouts/_default/_markup/render-image.html</summary>

```text
{{- $u := urls.Parse .Destination -}}
{{- $src := $u.String -}}
{{- if not $u.IsAbs -}}
  {{- with or (.Page.Resources.Get $u.Path) (resources.Get $u.Path) -}}
    {{- $src = .RelPermalink -}}
  {{- end -}}
{{- end -}}
{{- $attributes := dict "alt" .Text "src" $src "title" .Title -}}
<img
  {{- range $k, $v := $attributes -}}
    {{- if $v -}}
      {{- printf " %s=%q" $k $v | safeHTMLAttr -}}
    {{- end -}}
  {{- end -}}
>
{{- /**/ -}}
```
</details>

<details>
<summary>layouts/_default/_markup/render-link.html</summary>

```text
{{- $u := urls.Parse .Destination -}}
{{- $href := $u.String -}}
{{- if not $u.IsAbs -}}
  {{- with or
    ($.Page.GetPage $u.Path)
    ($.Page.GetPage (strings.TrimRight "/" $u.Path))
    ($.Page.Resources.Get $u.Path)
    (resources.Get $u.Path)
  -}}
    {{- $href = .RelPermalink -}}
    {{- with $u.RawQuery -}}
      {{- $href = printf "%s?%s" $href . -}}
    {{- end -}}
    {{- with $u.Fragment -}}
      {{- $href = printf "%s#%s" $href . -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
{{- $attributes := dict "href" $href "title" .Title -}}
<a
  {{- range $k, $v := $attributes -}}
    {{- if $v -}}
      {{- printf " %s=%q" $k $v | safeHTMLAttr -}}
    {{- end -}}
  {{- end -}}
>{{ .Text | safeHTML }}</a>
{{- /**/ -}}
```
</details>

Test site:

```text
git clone --single-branch -b hugo-github-issue-11933 https://github.com/jmooring/hugo-testing hugo-github-issue-11933
cd hugo-github-issue-11933
hugo server
```

### PR DESCRIPTION
**Pull request by bep**
Fixes #11933

### CODE REVIEW

**Comment by jmooring** [comment]
To avoid HTML5 validation "info" messages, we would need to remove the slash before the closing `>`.

image

**Comment by bep** [comment]
>To avoid HTML5 validation "info" messages, we would need to remove the slash before the closing >.

That was inserted by the Prettier formatter ... But I'll fix it.

**Comment by bep** [comment]
@jmooring this should work;

* The templates are almost identical to your proposed versions, I just dropped the "trim trailing slash" variant in GetPage and added that trim to the GetPage implementation.

**Review by jmooring — APPROVED** [review]

**Comment by jmooring** [comment]
> I just dropped the "trim trailing slash" variant in GetPage and added that trim to the GetPage implementation.

Thanks. That's great.

**Comment by jmooring** [comment]
For the record, I am quite pleased that we can now do this for every site, as needed:

```
[markup.goldmark.renderhooks.image]
enableDefault = true

[markup.goldmark.renderhooks.link]
enableDefault = true
```

For those serving sites from a subdirectory (e.g., most GitHub Pages sites) this will be a big help. And if they have images in static, just add:

```text
[[module.mounts]]
source = 'assets'
target = 'assets'

[[module.mounts]]
source = 'static'
target = 'assets'
```

Thanks!

**Pull request merged**
