### PR TITLE
[editorial] google_analytics.html: trim trailing whitespace from tpl actions

### PR DESCRIPTION
**Pull request by chalin**
"Editorial" change only: from `{{ ... }}` to `{{- ... }}`, to trim template action trailing whitespace.

### CODE REVIEW

**Comment by jmooring** [comment]
To be consistent with other embedded templates can we trim leading instead? For example:
<https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/schema.html>

**Comment by chalin** [comment]
Sure whatever convention you prefer.

**Comment by jmooring** [comment]
Trim leading please... thanks.

**Comment by chalin** [comment]
Ok, done ✨

**Review by jmooring — APPROVED** [review]
LGTM

**Pull request merged**
