### PR TITLE
Add basic pandoc support.

### PR DESCRIPTION
**Pull request by zackp30**
Add basic pandoc support, updated revision of #333.

### CODE REVIEW

**Comment by kotp** [comment]
:+1:  Though this has been open since November.

**Comment by anthonyfok** [comment]
@zackp30, would you like to follow up with refreshing your commit against the latest HEAD together with documentation?  :-)

**Comment by zackp30** [comment]
Crap, sorry, completely forgot.

**Comment by zackp30** [comment]
The code has changed quite a bit, I shall make a new PR in a bit.

**Comment by anthonyfok** [comment]
Hi @zackp30,

You do not need to make a new PR; rather, you may just make the necessary code changes, and then use git to force push your original branch to GitHub, and everything will be fine and dandy.  :-)

**Comment by gregwebs** [comment]
@zackp30 any chance you can rebase this to master?

**Pull request closed without merging**
