### PR TITLE
Always load GitHub Gists over HTTPS

### PR DESCRIPTION
**Pull request by coliff**
Specify gists to always load over HTTPS by specifying the protocol.

### CODE REVIEW

**Comment by bep** [comment]
Can you run `mage generate` to rebuild the Go templates?

**Comment by coliff** [comment]
I've never used Mage before - but I'll take a look....

**Comment by bep** [comment]
I can do it, no problem, but If you want to fiddle more with the Hugo source code, you might as well get that up and running. We should probably get it working with simpy `go generate`... but.

**Comment by coliff** [comment]
thanks :-) , yeah I would ideally like to get that up and running. I'm using Windows 10 Pro. In VS Code I ran (from the Hugo dir) :
```
git clone https://github.com/magefile/mage
cd mage
go run bootstrap.go
```
And I now have `mage.exe` in `C:\Users\coliff\go\bin`, but I'm unable to run the 'mage' command from command-line...I'll take another look at this later...

**Comment by bep** [comment]
>C:\Users\coliff\go\bin, but I'm unable to run the 'mage' command from command-line..

Yea, you need to get mage into your PATH env var somehow.

**Comment by coliff** [comment]
sorry I haven't managed to get Mage working yet. so could you pls rebuild the Go templates to merge this one?

**Pull request merged**
