### PR TITLE
tpl: Extend Jsonify to support options

### LINKED ISSUE #5040: Allow "jsonify" to pretty print JSON
"jsonify" currently uses json.Marshal which emits compact JSON.

We'd like to have the JSON output pretty printed (we're using Hugo for API documentation), so we need some function in Hugo that exposes json.MarshalIndent.

### PR DESCRIPTION
**Pull request by moorereason**
Fixes #5040

### CODE REVIEW

**Comment by bep** [comment]
I don't remember what we discussed in #5040 but thinking about it now I think I would prefer to use a dict option, e.g. `$foo  |  (dict "indent" "    ")`

Esp. if we should get more options in the future.

**Comment by moorereason** [comment]
PTAL

**Comment by zbayoff** [comment]
@moorereason  Thank you very much for this addition!! Is there any way you might update the Hugo Docs page as well to include the new options? https://gohugo.io/functions/jsonify/

**Comment by cshoredaniel** [comment]
I would suggest you checkout the Hugo Docs repo and add it yourself.  
That would take some load off the Hugo developers, and it's an open 
source project to enable / encourage collaboration...

**Pull request merged**
