### PR TITLE
chore: Update goreleaser syntax

### PR DESCRIPTION
**Pull request by jsoref**
* https://goreleaser.com/deprecations#nfpmsname_template

### CODE REVIEW

**Comment by bep** [comment]
Is this compatible with the version that Hugo uses to release?

**Comment by jsoref** [comment]
> since 2019-11-15, removed 2020-04-14 (v0.132.0)

Sorry, I can't figure out what version you're using.

I think you're using:
> bepsays/ci-goreleaser:1.14.3
> bepsays/ci-goreleaser:1.11-2

If I'm reading https://hub.docker.com/layers/bepsays/ci-goreleaser/latest/images/sha256-1336a48a7e8fdef1391d159ef92854f9a288b44c38e1199a78ab7e55b489794e?context=explore correctly, it looks like it's using:
> ENV GORELEASER_DOWNLOAD_URL=https://github.com/goreleaser/goreleaser/releases/download/v0.109.0/goreleaser_Linux_x86_64.tar.gz

https://github.com/goreleaser/goreleaser/commit/0953c2f4f76f0267cc26bd503e0f332b7d528aa3 appears to be present in v0.122.0

So, I think you'd need to bump ci-goreleaser:latest to run at least that version.

Hopefully @caarlos0 can confirm.

**Comment by caarlos0** [comment]
I think if Hugo's not missing any new features, there's not much of a point in upgrading... (except you want to) 

But, about what is available, I would suggest looking into the last release goreleaser's logs, it will show if deprecated configs were used... 🤔

**Comment by bep** [comment]
@caarlos0 I will, eventually ...

**Pull request closed without merging**
