### PR TITLE
commands: Support human-readable YAML boolean values in undraft

### PR DESCRIPTION
**Pull request by kropp**
Simplified version of #2831

### CODE REVIEW

**Comment by bogem** [comment]
Sorry for the stupid question, but how does it work, if it replaces nothing.

**Comment by kropp** [comment]
@bogem there is a loop over all frontmatter entries. Before this change, when `draft` key was found, it's value was changed from `true` to `false`. After this change this entry is skipped and not written to resulting frontmatter. Absent `draft` key means that the entry is not draft.

**Comment by bogem** [comment]
Ok, I understood.
When the docs should be also edited, because initially `undraft` command sets undraft field from true to false. Now you just delete. This should be noticed.

**Comment by bep** [comment]
How is `yes` interpreted by `go-yaml`?

**Comment by kropp** [comment]
@bogem thanks, nice catch! I've updated my change.

**Comment by kropp** [comment]
@bep all values according to [spec](http://yaml.org/type/bool.html) are supported: https://github.com/go-yaml/yaml/blob/v2/resolve.go#L37-L42

**Comment by bep** [comment]
@kropp that was not my question.

**Comment by kropp** [comment]
@bep `yes` is interpreted as `true`

**Comment by bogem** [comment]
Could you delete please the last line of help (`If the content's draft status is 'False', nothing is done.`). Your change removes the `draft` property despite the value.

**Comment by kropp** [comment]
@bogem No, `undraft` command does the check first and breaks if the given page is not draft (see https://github.com/kropp/hugo/blob/bf8aa82a5b638e88ba9529a26c7b81dfbda2e350/commands/undraft.go#L119-L122).

The documentation is therefore correct.

**Comment by bogem** [comment]
Ah ok, sorry for my inattention. 
Then it looks good to me.
What do you think, @bep?

**Pull request merged**
