### PR TITLE
images: Add AutoOrientation flag

### LINKED ISSUE #5181: Add support for image AutoOrientation
See https://github.com/disintegration/imaging/releases/tag/v1.5.0

### PR DESCRIPTION
**Pull request by Roganik**
When AutoOrientation flag set to true, image will be transformed
after decoding according to the EXIF orientation tag (if present).
This will help with cases when EXIF orientation tag is unexpectidly
overriden to default value.

Fixes #5181

### CODE REVIEW

**Comment by Roganik** [comment]
Hi, 

I've faced a problem that one of the images loses EXIF orientation when resized by Hugo. After digging I found the #5181 issue

I've tested my changes locally, and when I set the AutoOrientation to true my image keeps the original EXIF orientation as I expect.

I don't know if it's a breaking change or not, so I've set the default AutoOrientation to false to keep the default Hugo behavior unchanged. But honestly, I'd expect that the default value for AutoOrientation will be true, so other people won't need to figure out why their images have wrong orientation.

I'd love to hear a maintainer opinion on the default value AutoOrientation. And please let me know if I missed something.

Thanks

**Comment by bep** [comment]
I will happy to merge this if you can do it without introducing a new big image library.

**Comment by bep** [comment]
We should probably look a this in relation to #8586

**Comment by Roganik** [comment]
I considered two approaches: 
**1)** - always write the exif data that's lost on image modification (image.go -> doWithImageConfig)
but I didn't found good examples on writing exif data so I went with another approach.

**2)** - read orientation tag and rotate image per tag value in hugo image processing pipeline
I've implemented this approach. 
The caveat is that right now i don't support all orientation tag values. I support only one's that rotate image (3 = Rotate 180 ,6 = Rotate 90 CW ,8 = Rotate 270 CW ), and don't support the ones that mirror image (2 = Mirror horizontal, 4 = Mirror vertical, 5 = Mirror horizontal and rotate 270 CW, 7 = Mirror horizontal and rotate 90 CW).

It'll fix my use case: image shot on a phone and has Orientation = 6 = Rotate 90 CW.
But i'm not sure if it's an acceptable solution.

Bep, I'd love to know your thoughts before i continue working on a code.
Is second approach an acceptable or the first one is more desired? 

Thanks

_Note: i'm working on the top of Bep changes from https://github.com/gohugoio/hugo/compare/master...bep:feat/replace-exif-lib so review looks messy right now. (it mixes both Bep and my changes)_

**Comment by Roganik** [comment]
Oh, i found another lib [imageorient](https://github.com/disintegration/imageorient). It's a small lib that only handles image orientation and nothing more. 

Bep, will you merge changes if I use the small library [imageorient](https://github.com/disintegration/imageorient) instead of using big library [imaging](https://github.com/disintegration/imaging) and instead of writing custom rotation implementation? 

The changes will be similar to https://github.com/gohugoio/hugo/pull/8751/commits/2d13df885c5c1676d89e22caec7c73cf8b48a505

**Comment by Roganik** [comment]
I've used imageorient lib that only handles image orientation and nothing more.

Tested locally - it works.

**Comment by Roganik** [comment]
Bep, you've asked to not use big library, so I've added small one: [imageorient](https://github.com/disintegration/imageorient) that only handles image orientation and nothing more. It's the lib of the same author that wrote [gift](https://github.com/disintegration/gift) image processing library that's already used in Hugo.

@bep Can you please advice if this changes are good to be merged?

If they do, I'll rebase the changes and re-check code.
If my code needs some polishing - I'm open to feedback.
If you don't wish to merge such changes please let me know so I can close this PR.

Thanks

**Comment by bep** [comment]
I'm not adding more dependencies to get this done (we do not want to read the Exif info twice, for once).

**Pull request closed without merging**
