### PR TITLE
Added support for CoffeeScript

### PR DESCRIPTION
**Pull request by flipacholas**
The new pipe proposed is inspired by the recent addition of babel (#7223 and #5772) and uses the coffeescript cli to interact with the compiler.

This pull requests just adds the bindings, tests and docs.

#### Usage

```
{{- $transpiled := resources.Get "scripts/main.coffee" | coffee  -}}
```

With options:

```
{{ $opts := dict "outputPath" "js/main.js" }}
{{- $transpiled := resources.Get "scripts/main.coffee" | coffee $opts -}}
```

Inlined:

```
{{- $transpiled := resources.Get "scripts/main.coffee" | coffee -}}
<script>{{- $transpiled.Content | safeJS -}}</script>
```

Referenced:

```
{{ $opts := dict "outputPath" "js/main.js" }}
{{- $transpiled := resources.Get "scripts/main.coffee" | coffee $opts -}}
<script src="{{- $transpiled.RelPermalink -}}"></script>
```

### CODE REVIEW

**Comment by bep** [comment]
Thanks for this, but this should now be supported (natively) in https://gohugo.io/hugo-pipes/js/#readout

**Comment by flipacholas** [comment]
@bep I think that's Typescript, not Coffeescript

**Comment by flipacholas** [comment]
But yeah, I guess javascript processing is now delegated to esbuild, including language support

**Comment by bep** [comment]
OK, you are right about the coffescript vs typescript -- but Hugo will never be a project that can support JS in all flavours.

**Pull request closed without merging**
