### PR TITLE
deps: upgrade github.com/alecthomas/chroma v0.9.4 => v0.10.0

### PR DESCRIPTION
**Pull request by robherley**
👋 chroma [`v0.10.0`](https://github.com/alecthomas/chroma/releases/tag/v0.10.0) was released and has some updates i'm looking to use on my hugo site

### CODE REVIEW

**Review by bep — APPROVED** [review]

**Comment by bep** [comment]
Thanks, I'll merge this once the build go green. One comment re the commit message; according to our guidelines (which I know is a little different than some other projects) it should read "deps: Upgrade ...", but don't worry, I'll fix it when I merge.

**Comment by bep** [comment]
There's some potentially breaking changes in this Chroma release (ref. the test failures) which I cannot merge without carefully consideration as it will certainly need some stylesheet updates in the wild.

**Comment by robherley** [comment]
Looks like it was due to these PRs: 

- https://github.com/alecthomas/chroma/pull/571
- https://github.com/alecthomas/chroma/pull/572

**Comment by anthonyfok** [comment]
Superseded by:
* #9500
which contains fixes to tests to match the minor output changes introduced in chroma v0.10.0.

**Pull request closed without merging**
