### PR TITLE
Switch from cssmin to minify

### PR DESCRIPTION
**Pull request by jorinvo**
Switch from *cssmin* to _minify_ because _cssmin_ is not maintained since four years
and _minify_ is actively developed.
It also minifies better (see https://gist.github.com/jorinvo/ecf2feb6f105a224c67ea9bc084072f1).

### CODE REVIEW

**Comment by moorereason** [comment]
You should remove cssmin from vendor.json.

**Comment by jorinvo** [comment]
Thanks @moorereason, don't know how I missed that 😄

**Comment by moorereason** [comment]
Also, if you intend to be submitting more patches in the future, please learn to follow our [git commit message guidelines](https://github.com/gohugoio/hugo/blob/master/CONTRIBUTING.md#git-commit-message-guidelines).  In this case, I'd suggest:

```
hugolib: Switch from cssmin to minify

cssmin has not been maintained for four years while minify is actively maintained.
It also minifies better.

Fixes #3761
```

**Comment by jorinvo** [comment]
@moorereason Thanks, I updated the commit message accordingly.
Only that this PR is not a fix for #3761.

**Pull request closed without merging**
