### PR TITLE
fix RelURL and AbsURL when path starts with language

### PR DESCRIPTION
**Pull request by ivan-meridianbanc-com**

### CODE REVIEW

**Comment by ivan-meridianbanc-com** [comment]
@bep

**Comment by bep** [comment]
What is this trying to fix? Can you give some "failing examples"?

**Comment by ivan-meridianbanc-com** [comment]
Example:
language: de
url: deposit
Expected: de/deposit
Actual: deposit

There are test in the pull request.

**Comment by ivan-meridianbanc-com** [comment]
So for a site baseURL set to https://example.com/hugo/ and the current language is en:

{{ "blog/" | relLangURL }} → "/hugo/en/blog/"

**Comment by ivan-meridianbanc-com** [comment]
> What is this trying to fix? Can you give some "failing examples"?



> So, you meant that `{{ "deposit" | relURL }}` should be `/de/deposit`?
> 
> `relURL` does not take language into account, I don't see how it could. See
> 
> https://gohugo.io/functions/rellangurl/

https://gohugo.io/functions/rellangurl/

relLangURL and absLangURL take language into account

{{ "blog/" | absLangURL }} → "https://example.com/hugo/en/blog/"
{{ "blog/" | relLangURL }} → "/hugo/en/blog/"

blog/ becomes /hugo/en/blog/
the problem is that if the language is de and the parameter (blog/ from example above) starts with de (example deposit) hugo thinks it is already added the prefix, but it don't and the url becomes
/deposit instead of /de/deposit

Could you please, merge this Pull Request ?

**Comment by a-andre** [comment]
@bep what's necessary to get this merged?

Gajim website is affected, see https://dev.gajim.org/gajim/website/issues/25

**Comment by ivan-meridianbanc-com** [comment]
@spf13 Could you please tell me what I need to do this pull request to be merged ?

**Comment by ivan-meridianbanc-com** [comment]
@anthonyfok Could you please tell me what I need to do this pull request to be merged ?

**Comment by ivan-meridianbanc-com** [comment]
> > What is this trying to fix? Can you give some "failing examples"?
> 
> > So, you meant that `{{ "deposit" | relURL }}` should be `/de/deposit`?
> > `relURL` does not take language into account, I don't see how it could. See
> > https://gohugo.io/functions/rellangurl/
> 
> https://gohugo.io/functions/rellangurl/
> 
> relLangURL and absLangURL take language into account
> 
> {{ "blog/" | absLangURL }} → "https://example.com/hugo/en/blog/"
> {{ "blog/" | relLangURL }} → "/hugo/en/blog/"
> 
> blog/ becomes /hugo/en/blog/
> the problem is that if the language is de and the parameter (blog/ from example above) starts with de (example deposit) hugo thinks it is already added the prefix, but it don't and the url becomes
> /deposit instead of /de/deposit
> 
> Could you please, merge this Pull Request ?

@bep 
I provided the example from the documentation that relLangURL and absLangURL add the language to the url.
But there is a bug when the url the the example "blog" in my example "deposit" starts with language example "de". "deposit" starts with "de" and the code skips to add "/de/deposit", but becomes "/deposit".
For english it works correctly "/en/deposit".

Please, tell me what is needed to merge this ?
Or if you do not think that this is correct please let me know so I can make changes to merge request.

**Comment by wurstsalat3000** [comment]
Hi, I visit again because this bug still affects us when trying to deploy content with i18n on gajim.org. I just tested with vanilla Hugo 0.64.1, and the bug is still present, see following example:

* How it should be: `website.tld/de/development`
* How it actually is: `website.tld/development` (thus falling back to original EN content, instead of DE)

However, manually applying the patch from this MR fixes the bug (tested using Hugo 0.64.1).

**Comment by Steiniche** [comment]
Experiencing the same problem with URL /data/ on language da (Danish).
@bep what is needed to get this put into a release?
Is there something we can do?

**Comment by wurstsalat3000** [comment]
*Yes*, this is still a problem which needs to be fixed. I just tested this with Hugo 0.73. This pull request provides a working fix for the problem. I manually patch hugo every time I update it on the server.

I understand using StaleBot might be a solution to reduce the count of open issues. Managing an issue tracker is time consuming and needs a lot of maintenance from my experience. But you really shouldn’t apply StaleBot on *pull requests*. After all, people invested their time to fix/add something they found are worth spending time on.

**Comment by ivan-meridianbanc-com** [comment]
@bep
Please, what should be done to merge this pull request?

I really like your product and I use it on every day.
I just want to contribute to make it a little better.

Please, cloud you merge this fix for a bug?

**Comment by bep** [comment]
OK, sorry for the delay. I misunderstood this the last time I looked at it.

**Comment by Steiniche** [comment]
Thanks for merging this @bep 
Is there any timeline on when this will be included in a release?

**Comment by bep** [comment]
>Is there any timeline on when this will be included in a release?

No, statistically I would have needed to do a patch release fixing a regression from 0.79, but that hasn't happened... If you need this right away, it's fairly easy to build from source.

**Comment by bep** [comment]
... that said, the release frequency is pretty high ...

**Pull request merged**
