### PR TITLE
use filename or title header when not defined in frontmatter

### PR DESCRIPTION
**Pull request by maxandersen**
this is initial proposed fix for https://github.com/gohugoio/hugo/issues/3805

has changes also done in https://github.com/gohugoio/hugo/pull/3762 which this PR is dependent on.

NOTE: I want to clean this up with some better tests and better handling of the differences
between various formats, but wanted to show the general idea for feedback.

### CODE REVIEW

**Comment by maxandersen** [comment]
updated to just fix using filename (or slug) to derive title.

**Comment by jbleuzen** [comment]
I was waiting this PR to migrate from Jekyll to Hugo, I don't want add dates in FrontMatter from my filenames...

Please don't close this. How can I help to get it merge ?

**Comment by maxandersen** [comment]
as @jbleuzen says - this is useful for migration and generallly reduces need for duplication.

**Comment by jbleuzen** [comment]
@maxandersen not sure if this might help to see this PR merged, but it seams you didn't sign the Contributor License Agreement.

**Comment by maxandersen** [comment]
cla is now signed.

**Comment by maxandersen** [comment]
sorry for reacting late (vacations :) 

avoiding having to specify title in frontmatter still seem to not have been implemented thus this one is still relevant imo.

**Pull request closed without merging**
