### PR TITLE
Add `wp2hugo` reference

### PR DESCRIPTION
**Pull request by ashishb**

### CODE REVIEW

**Comment by jmooring** [comment]
As stated in this project's [README](https://github.com/gohugoio/hugo?tab=readme-ov-file#contributing):

> Please submit documentation issues and pull requests to the [documentation repository](https://github.com/gohugoio/hugoDocs).

**Comment by ashishb** [comment]
@jmooring I signed the CLA

**Comment by jmooring** [comment]
See my previous comment. You submitted the PR to the wrong repository.

**Comment by ashishb** [comment]
My bad @jmooring. Submitted another PR https://github.com/gohugoio/hugoDocs/pull/2502

**Pull request closed without merging**
