### PR TITLE
Removed unreachable link

### PR DESCRIPTION
**Pull request by mahajanrajan**

### CODE REVIEW

**Comment by coliff** [comment]
Related: https://github.com/igrigorik/ga-beacon/issues/81

If the tracking image is being removed then the link should be removed from the README too.

**Comment by bauripalash** [comment]
> Related: [igrigorik/ga-beacon#81](https://github.com/igrigorik/ga-beacon/issues/81)
> 
> If the tracking image is being removed then the link should be removed from the README too.

Demo instance of <https://github.com/igrigorik/ga-beacon> is down, and no reply from maintainer(s) yet.

So it's best to selfhost, it is also recommended in the project's Readme.

**Comment by bep** [comment]
I'm pretty sure I merged this in another PR.

**Comment by mahajanrajan** [comment]
I am really sorry for it,
can you please add hacktoberfest-accepted
@bep

**Comment by coliff** [comment]
@mahajanrajan Closed PRs aren't counted for Hacktoberfest - even if they have the hacktoberfest-accepted label.

**Comment by mahajanrajan** [comment]
@coliff No problem sir. 😊

**Pull request closed without merging**
