### PR TITLE
Add goldmark-mathjax

### PR DESCRIPTION
**Pull request by xjzsq**
See #6694 
I created this PR to add the extension of goldmark [goldmark-mathjax](https://github.com/litao91/goldmark-mathjax).  
In current Hugo, if I want to use Mathjax, I must make some changes to the mathematical formula, for example change `\\` to `\\\\` because of markdown will convert `\\` to `\`. Now I can configure Markup like this to enable goldmark-mathjax plugin ( this plugin is enable by default ) :  
``` toml
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark]
        [markup.goldmark.extensions]
            mathjax = true
```
This PR fixed these bugs in Mathjax by adding goldmark-mathjax to Hugo.  
Another example: ( from @awwong1's comment in #6694 )  
From markdown:  
``` markdown
$$
\mathbb{E}(X) = \int x d F(x) =
\left\{ \begin{aligned} \sum_x x f(x) \; & \text{ if } X \text{ is discrete}
\\ \int x f(x) dx \; & \text{ if } X \text{ is continuous }
\end{aligned} \right.
$$
Inline math $\frac{1}{2}$
```  
Default settings would currently output:
```html
<p>$$
\mathbb{E}(X) = \int x d F(x) = \left{ \begin{aligned} \sum_x x f(x) ; &amp; \text{ if } X \text{ is discrete}
\ \int x f(x) dx ; &amp; \text{ if } X \text{ is continuous }
\end{aligned} \right.
$$</p>
<p>Inline math $ \frac{1}{2} $</p>
```
With the goldmark-mathjax plugin enabled (inline: $, block: $$), you'd see:
``` html
<p><span class="math display">$$\mathbb{E}(X) = \int x d F(x) =
\left\{ \begin{aligned} \sum_x x f(x) \; &amp; \text{ if } X \text{ is discrete}
\\ \int x f(x) dx \; &amp; \text{ if } X \text{ is continuous }
\end{aligned} \right.
$$</span></p>
<p>Inline math <span class="math inline">$\frac{1}{2}$</span></p>
```

### CODE REVIEW

**Comment by awwong1** [comment]
I made this PR a while ago, but it was rejected due to the no CGO rule.
https://github.com/gohugoio/hugo/pull/6842

**Comment by AndreyAkinshin** [comment]
What's the current status of this PR? It would be awesome to have [goldmark-mathjax](https://github.com/litao91/goldmark-mathjax) support out of the box.

**Comment by jph00** [comment]
Addresses #6694

**Comment by jph00** [comment]
@xjzsq in case this PR isn't merged, would you be able to let me know how to update it to use the latest version of the `goldmark-mathjax` module?

**Comment by jph00** [comment]
@xjzsq n/m I figured it out. I'll plan to maintain a fork with a current patch here until/unless it's merged:
https://github.com/fastai/hugo/

**Comment by gadams999** [comment]
@xjzsq - thanks for this PR, it was helpful to get another extension, [goldmark-plantuml](https://github.com/OhYee/goldmark-plantuml) working too. I used to use Asciidoctor to render plantuml but this approach works for development too.

I'll open a new PR to start discussing, but this as #6842 got me over the hump!

**Comment by xjzsq** [comment]
I found that [litao91/goldmark-mathjax](https://github.com/litao91/goldmark-mathjax) conflicts with the "$" variable in Hugo, so I refactored its code: [xjzsq/goldmark-mathjax](https://github.com/xjzsq/goldmark-mathjax) and will submit a new PR

**Comment by AndreyAkinshin** [comment]
This feature request is still actual.

**Comment by jmooring** [comment]
Closing in favor of #10894.

**Pull request closed without merging**
