### PR TITLE
doc: Add hugo-lyra to static open-source search engines

### PR DESCRIPTION
**Pull request by paolomainardi**
Hi everyone! 

As the title suggests, I am adding a new library I am working on to integrate [Lyra search](https://github.com/LyraSearch/lyra) into a Hugo website.

I wrote this post to explain a bit more in depth: https://www.paolomainardi.com/posts/hugo-search-engine-lyra/

### CODE REVIEW

**Comment by paolomainardi** [comment]
Does anyone have time to look at this?

**Comment by jmooring** [comment]
Please resubmit to the documentation repo.
<https://github.com/gohugoio/hugoDocs>

**Comment by paolomainardi** [comment]
ok thanks @jmooring

**Comment by paolomainardi** [comment]
done https://github.com/gohugoio/hugoDocs/pull/1959

**Pull request closed without merging**
