### PR TITLE
tools: Deploy to cloud using ansible

### PR DESCRIPTION
**Pull request by souvikhaldar**
Add ansible script and helper scripts to easily deploy a static site created using Hugo to Debian based servers on any cloud service provider. I have personally used this tool and still do, to deploy the changes my website content to the digital ocean droplet. Reference:- http://souvikhaldar.info/

I believe this should be useful for beginners as well as experts to easily put their changes to cloud and run the Hugo server as systemd service (for obvious reasons) all in one command.

### CODE REVIEW

**Comment by bep** [comment]
Thanks, but we cannot add this to this repo.

**Comment by souvikhaldar** [comment]
May I ask you why? @bep

**Comment by souvikhaldar** [comment]
> Thanks, but we cannot add this to this repo.

May I ask you why?

**Comment by bep** [comment]
>May I ask you why?

It does not belong here. There are millions of ways to deploy to the cloud, we cannot maintain scripts for all of them in this repo. That would be way too much work for this small team.

**Pull request closed without merging**
