### PR TITLE
tpl/tplimpl: Update RSS template

### LINKED ISSUE #3918: RSS template should use `PublishDate`
``` 
<pubDate>{{ .Date.Format "Mon, 02 Jan 2006 15:04:05 -0700" | safeHTML }}</pubDate>
```

### LINKED ISSUE #11692: Add Hugo version to RSS </generator>
From: https://ftw.lol/index.xml

Notice element `</generator>`.
```
<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
<channel>
<title>FTW.LOL</title>
<link>//ftw.lol/</link>
<description>Recent content on FTW.LOL</description>
<generator>Hugo -- gohugo.io</generator>
<language>en</language>
<copyright>© 2023 FTW.LOL</copyright>
<lastBuildDate>Tue, 12 Sep 2023 00:00:00 +0000</lastBuildDate>
<atom:link href="//ftw.lol/index.xml" rel="self" type="application/rss+xml"/>
<item>
```
So we know what version we refer to. See #11691

### PR DESCRIPTION
**Pull request by jmooring**
- Use publication date for pubdate
- Include version in generator element

Closes #3918
Closes #11692

### CODE REVIEW

**Comment by johnweldon** [comment]
fwiw, it doesn't appear that `PublishDate` falls back to `Date` if it's not set - at least not for Categories and Tags.

**Comment by jmooring** [comment]
@johnweldon If you think there's a bug, log a bug.

**Comment by thc202** [comment]
Would be possible to have the version optional? We serve the site through GitHub Pages which lives in its own repo, with the version change we end up with unnecessary pull requests just updating the version (e.g.: https://github.com/zaproxy/zaproxy.github.io/pull/1425/files).

**Comment by schu** [comment]
> it doesn't appear that `PublishDate` falls back to `Date` if it's not set - at least not for Categories and Tags.

I noticed this as well and opened an issue here: https://github.com/gohugoio/hugo/issues/12438

**Pull request merged**
