### PR TITLE
extras/shortcodes: Add Reuse Page Shortcode concept

### PR DESCRIPTION
**Pull request by savsheniuk**
Add a Reuse Page shortcode that allows tech writers to reuse same pages in different places without need in copy-pasting them every time.
It also adds a concept of Page snippets and dynamic links resolution.

### CODE REVIEW

**Comment by savsheniuk** [comment]
selection_084

**Comment by moorereason** [comment]
@savsheniuk,
The problem with the CLA is likely that your git commits use a different email address than your GH account.

**Comment by savsheniuk** [comment]
@moorereason Oh, yes. You are right :(

**Comment by bep** [comment]
Hey and welcome to Hugo devs, @savsheniuk !

I have read your code, and it looks solid. So, I understand that you are a good developer.

But I'm not sure how this fits into the "vision" #3205, and a number of changes tell me that I don't want to commit to this right now.

I would probably have preferred to make it simpler:

* Just mark them as snippets in a front matter and put them in a temporary collection and just look in all page collections when referenced (in some order)
* Instead of some new shortcode syntax, I would prefer just to create a Hugo internal shortcode (`hugo-snippet` or whatever, with a reserved namespace).

But even with those simplifications, I'm hesitant at the moment. 

But what would have been a good idea, and I feel it would solve the same problem, would be some kind of _caching internal decorator shortcode_, so I would do something like this:

```
{{< hugo-cached >}}
{{< readAndMarkdownify filename="/some-file.md" >}}
{{< /hugo-cached >}}
```

Where `hugo-cached` would be a special internal shortcode that would somehow use all the parameters for the inner shortcodes as a cache key.

**Comment by savshen** [comment]
Thanks, @bep . I understand your concern. Just one note that markdownify function doesn't handle shortcodes in the specified page and in order to do that I needed to get to the context of the page rendering... so the decision was to do that on the stage of the shortcodes processing what pointed me onto writing a new kind of shortcode that works as any other shortcode but allows to use the content of the page as an inner content... it looked to me as a pretty generic solution... although I spontaneously added a few other features to that shortcode like Dynamic links processing and Page snippets.... so now it could seem a little overflown...

**Comment by savshen** [comment]
Fixed the first point: new parameter "issnippet=true" can be specified inside the front-matter to mark the page as a snippet.

**Comment by bep** [comment]
I will close this as I think this is too big a change for what it is.

Most of this will be gained from  #3612

**Pull request closed without merging**
