### PR TITLE
Respect ignoreFiles config setting for static files

### LINKED ISSUE #1559: IgnoreFiles for static folder
As discussed here
http://discuss.gohugo.io/t/slow-to-work-with-large-number-of-static-files/2046

Update `IgnoreFiles` to also affect files in the `static` folder.

### LINKED ISSUE #4874: ignoreFiles does not work as documented
I cannot get the example from the documentation of `ignoreFiles` to work in a brand new project.

Using Hugo 0.41 on macOS 10.11.6, I created a new site using `hugo new site testing` and added the following to `config.toml` [as per the documentation of `ignoreFiles`](http://gohugo.io/getting-started/configuration/#ignore-files-when-rendering):

```toml
ignoreFiles = [ "\\.foo$", "\\.boo$" ]
```

The documentation says that this should

> cause Hugo to ignore files ending with `.foo` and `.boo` when rendering

but when I create a file at the path `static/example.foo` and run `hugo`, it is copied to `public/example.foo`, i.e. not ignored at all.

It seems that either there is a bug in Hugo or the documentation must be updated.

### PR DESCRIPTION
**Pull request by stapelberg**
fixes #1559
fixes #4874

### CODE REVIEW

**Comment by stapelberg** [comment]
The travis failure affects windows only and seems unrelated to my change.

**Comment by stapelberg** [comment]
Friendly ping?

**Comment by marrrcin** [comment]
This would be a nice feature to merge

**Comment by vvasuki** [comment]
indeed- I don't want to have to write a script to manually delete ignored files. :-(

**Comment by stapelberg** [comment]
@spf13 @bep friendly ping? :)

**Comment by hartzell** [comment]
ping?

**Comment by XhmikosR** [comment]
This is still valid, but needs a rebase

**Comment by stapelberg** [comment]
> This is still valid, but needs a rebase

Rebased onto current master.

**Comment by XhmikosR** [comment]
@bep friendly ping :)

**Comment by bep** [comment]
To my knowledge, `ignoreFiles` has always been just `content` files.  I have updated the docs to reflect this. This means that we cannot repurpose that same setting to also include some other random files without breaking sites in the wild. Assuming I have this in my config:

```
ignoreFiles = [ "\\.jpg$" ]
``` 

I wanted to ignore /content/blog.jpg, but certainly not /static/images/cat.jpg or /assets/images/cat.jpg.

**Comment by bep** [comment]
That said, I do understand the need for all of this, and I agree that doing this on this as a file system wrapper makes sense.

But I don't want us to build this on top of some legacy config when it doesn't match particularly well.

I'm doing some work adding Goldmark as the new default Markdown renderer now, and 90% of that work is to split what we have into packages.

So, what I suggest we do is to add a new config element called `files`:

```toml
[files]
[[files.ignore]]
fileSystem = "static" (or "all"?)
expressions = [ "\\.jpg$" ]
[files]
[[files.ignore]]
fileSystem = "content")
expressions = [ "\\.jpg$" ]
```

See https://github.com/gohugoio/hugo/blob/master/hugofs/files/classifier.go#L76 for the "file system classifiers".


And then decode that config into `files.Config` and use that when building the different filesystems.


https://github.com/gohugoio/hugo/blob/master/hugofs/files/classifier.go#L76

**Comment by stapelberg** [comment]
I don’t have time to make these changes right now. Could someone else jump in and move this forward please?

**Comment by ackerleytng** [comment]
Looking forward to having this merged!

**Comment by XhmikosR** [comment]
This is still valid.

**Comment by marrrcin** [comment]
I agree, this PR was opened on `29 Jan 2019`...

**Comment by XhmikosR** [comment]
Still valid.

**Comment by raspopov** [comment]
Any news?

**Comment by jmooring** [comment]
This was resolved with https://github.com/gohugoio/hugo/pull/9059.

```
[[module.mounts]]
source = 'static'
target = 'static'
excludeFiles = '*.txt'
```

See <https://gohugo.io/hugo-modules/configuration/#module-config-mounts>

**Pull request closed without merging**
