### PR TITLE
Add support for native Go implementation of AsciiDoc by using libasciidoc

### LINKED ISSUE #1435: Add support for native Go implementation of AsciiDoc
Starting with v0.14 (released in May 2015), Hugo provides preliminary support for AsciiDoc with the help of an external helper such as `asciidoc` (Python-base) and `asciidoctor` (Ruby-based).

Please see Issue #470 "Support for AsciiDoc" (which led to the current experimental "external helper" implementation) for more information.  This issue 

However, the ultimate goal is for Hugo to support a native Go implementation of AsciiDoc, something that e.g. the https://github.com/VonC/asciidocgo project set out to accomplish.  This issue will track the progress on that front.

### PR DESCRIPTION
**Pull request by odknt**
Close #1435

Render asciidoc by using [libasciidoc](https://github.com/bytesparadise/libasciidoc) if `useLibasciidoc` is true.

### CODE REVIEW

**Comment by moorereason** [comment]
We're aware of the `libasciidoc` project, but I don't think it's ready for production yet.

Cc: @xcoulon

**Comment by bep** [comment]
0.1 may be a little early, yes -- but @xcoulon has been very busy lately. I'm very impressed by his recent work. I'm not familiar with AsciiDoc, so I cannot judge when this has become "good enough", but I can say this:

* My thought has always that the current AsciiDoc handling is something temporary until something native happens. So, when we do add this to Hugo, the native implementation will be the default, with a flag to use "the old".

**Comment by xcoulon** [comment]
thanks for this PR @odknt, it was actually on my TODO list for a little later, once libasciidoc would have a better support of the Asciidoc syntax. And the plan is actually to use a feature toggle (as you did) to make sure that it's set at an "experimental" level for a bit (while Asciidoctor would remain the default runtime to process the files).

Thanks for the feedback @bep! I hope I can get more features soon (as time allows), and we should definitely discuss about the info/metadata that libasciidoc should return upon processing. I'm thinking about the doc title, author and ToC for instance, but there may be also other pieces of info that it should return to integrate nicely in Hugo.

**Comment by odknt** [comment]
@bep @moorereason @xcoulon Thanks for checking.

May be @moorereason is right. I found issue related asciidoc in hugo and libasciidoc.
I may need to fix them ahead of this PR.

* `{{ .TableOfContents }}` not working in asciidoc (#1687).
* libasciidoc in panic rendering TOC if no sections.

Is there a possibility to be merge this PR?
In that case I want to add commit that use `parser` and `renderer/html5` instead of `libasciidoc.ConvertToHTML()` for TOC support.

**Comment by xcoulon** [comment]
> * libasciidoc in panic rendering TOC if no sections.

@odknt if you found a bug in libasciidoc, would you mind opening an issue with a sample content so I can reproduce and fix the bug, please? I probably missed an edge-case with regards to the ToC ;)

**Comment by bep** [comment]
>Is there a possibility to be merge this PR?

This will have to wait. Mostly to wait for libasciidoc to be a little more mature (it looks really promising). That, and I'm currently working on some restructuring of the relevant code, which will make this integration simpler when this is ready. But thanks for your contribution.

**Comment by odknt** [comment]
OK, thanks.

**Comment by xcoulon** [comment]
> > * libasciidoc in panic rendering TOC if no sections.
> 
> @odknt if you found a bug in libasciidoc, would you mind opening an issue with a sample content so I can reproduce and fix the bug, please? I probably missed an edge-case with regards to the ToC ;)

The ToC bug in libasciidoc was fixed in https://github.com/bytesparadise/libasciidoc/issues/284

**Pull request closed without merging**
