### PR TITLE
Spelling: rysnc -> rsync

### PR DESCRIPTION
**Pull request by eest**

### CODE REVIEW

**Comment by digitalcraftsman** [comment]
Hello @eest,

thank you for fixing this typo. In order to get your submission merged contributors have to sign the contributor license agreement by clicking on the yellow badge in the comment above.

Cheers,
Digitalcraftsman

**Comment by eest** [comment]
@digitalcraftsman: it's done :)

**Comment by digitalcraftsman** [comment]
Quick note: pull request that are only documentation-related, i.e. don't contain any code changes, shall be submitted to the hugoDocs repository instead.

I've merged you commit there as https://github.com/gohugoio/hugoDocs/commit/fac55121bc921e16ab24f2062bf61e67cb96e123.

**Comment by eest** [comment]
Thanks for the info!

**Pull request merged**
