### PR TITLE
Add an option to trim trailing slashes from URLs

### PR DESCRIPTION
**Pull request by jamieconnolly**
It lives behind a `trimTrailingSlash` option in `config.toml`. There is no CLI flag for this option.

It works by hooking into the `uglyURLs` functionality and then stripping out the `.html` suffix when generating URLs. This means it generates `/filename.html` files rather than `/filename/index.html`. It also handles when there's no trailing slash in the page's URL when set through the front matter.

It's all been tested, but if there are any I've missed please let me know.

I've documented the option in my fork of hugoDocs. I'll create a PR if/when this progresses.

See #3556 and https://discuss.gohugo.io/t/links-without-a-trailing-slash/831.

### CODE REVIEW

**Comment by jamieconnolly** [comment]
I forgot to mention that this is now ready to review.

**Comment by betaveros** [comment]
Any updates on this? I'd love to see this feature in Hugo.

**Comment by DandyDev** [comment]
I'd love to see this merged. I want to migrate my website from Pelican to Hugo, but I want to keep the URLs in tact. And those URLs currently don't have trailing slashes.

**Comment by bep** [comment]
I will have to think about this one. The change set was a little bit bigger than I imagined. It looks correct, but I'm not sure I'm willing to maintain such a feature.

**Comment by DandyDev** [comment]
With the risk of reopening the whole discussion I saw on Discourse: I understand why the way Hugo currently works is really convenient, because it requires no changes to your webserver. But the reasoning behind the trailing slash just isn't valid 100% of the time.
If you don't need to have a separate directory per blog post, because you have no need for extra files (images, different formats, etc.), you should be able to generate a `.html` file per blog post, all in 1 directory. And in that case, trailing slashes would be breaking the rules.

This is my current setup in Pelican:

```
blog/post-1.html -> https://example.com/blog/post-1
blog/post-2.html -> https://example.com/blog/post-2
...
```
NGINX is configured in such a way that it will serve `blog/post-1.html` when `blog/post-1` is requested.

This is a valid usecase I'd think, right?

**Comment by mapx** [comment]
It's a great feature request that worth waiting to be accepted or refused by human.

**Comment by storix** [comment]
Too sad this isn't merged. Actually, what Hugo calls "ugly urls" is called "pretty urls" on Netlify. Take a look at [their docs](https://www.netlify.com/docs/redirects/#trailing-slash):

> When “Pretty URLs” is enabled under processing settings for your site, Netlify will enforce consistent URL patterns.
> 
> A link to /about.html will be rewritten to /about in your HTML files and Netlify will enforce a redirect from /about/ to /about

It seems urls w/o trailing slashes are a standard in the modern web development. For God's sake, even this very PR url is **without** a trailing slash.

**Comment by kaushalmodi** [comment]
@storix 

> Too sad this isn't merged. Actually, what Hugo calls "ugly urls" is called "pretty urls" on Netlify. 

The "prettiness" definition is slightly different, but not the opposite.

Both Hugo and Netlify consider URLs ending in `.html` as Ugly. That part is consistent.

The only thing is that Hugo doesn't care about removing the trailing slash for non-Ugly URLs, while Netlify removes the trailing slashes too.

FWIW I don't care much about the trailing slashes being present or not.. Why is that a big deal.. just URL aesthetics or a technical reason?

**Comment by storix** [comment]
@kaushalmodi 

> The "prettiness" definition is slightly different, but not the opposite.

Honestly, I find all these config options regarding url prettiness quite confusing. Maybe it's better to rename  `uglyUrls` to something more meaningful. But, okay, this is a different topic.

> FWIW I don't care much about the trailing slashes being present or not.. Why is that a big deal.. just URL aesthetics or a technical reason?

It's a big deal when you are migrating a site which was already configured with "slashless" urls. Search engines treat `https://example.com/blog/post/` and `https://example.com/blog/post` as different urls. Currenlty I need to search through the web for some hacks that will force Hugo to remove the trailing slashes.

**Comment by DandyDev** [comment]
Interesting that this issue is considered "stale", because the maintainers just chose to ignore it. Many compelling arguments have been put forth, but apparently that is not good enough...

**Comment by anthonyfok** [comment]
@DannyDev wrote:
> Interesting that this issue is considered "stale", because the maintainers just chose to ignore it.

Well, things are not what they appear on the surface.  A few observations from an occasional helper:

* An issue or a PR becomes stale when there is no activity on it for several months, and as you can see, the "stale" tag was added automatically by a bot without no human intervention.
* While it is a bit sad when an issue or a PR goes stale, it serves as a wake-up call because interested parties including the original submitter will notice the "stale" state, and that is usually enough to spurge everyone into action, if people care about the issue/PR enough.
* Hugo has gone through tremendous evolution over the past year with lots of exciting new features as well as bug fixes, and I am really amazed by what our Lead Maintainer has accomplished.  That said, all maintainers and contributors, including our Lead, are volunteers, and are human.  There is a limitation of how much one can accomplish in a day, and there are lots of issues and PRs that still need to be looked after but would have to wait due to lack of manpower.  It is like that in almost all open-source projects, so I hope you can understand.
* It seems the CLA (Contributor License Agreement) isn't signed?  Was that the case even before this PR went stale?  If that is the case, that would be a major obstacle which prevents the PR from being accepted.
* For better or for worse, 10 months have passed since the initial PR, and due to Hugo's major new features and refactoring, there are now merge conflicts that need to be resolved.

**Comment by betaveros** [comment]
As you can see from the GitHub notification, I tried rebasing this PR onto master. I didn't get to rebasing all the tests yet, but the feature seems to work overall if I manually test against my own static site and, if it would be enough to get this merged, I can try to rebase the tests or write equivalent ones in a few days. (Are there licensing issues? The original author has made a PR before https://github.com/gohugoio/hugo/pull/3933 and the CLA bot reports that they signed the CLA there; I also think I signed the CLA when submitting previous PRs, but the bot no longer seems to think that I have.) I still care a good deal about this feature and consider it essential for me to use Hugo, FWIW.

(Incidentally, Hugo is orders of magnitude faster for me since the rebase — kudos to the maintainers' effort!)

The diff so far is here: https://github.com/gohugoio/hugo/compare/master...betaveros:trim-trailing-slash

**Comment by ngocketit** [comment]
Any update on this please? Having URLs with a slash is a stopper for me to migrate a site to Hugo now :(

**Comment by hanzei** [comment]
@ngocketit Could you please elaborate why this is a blocker for you?

**Comment by ngocketit** [comment]
@hanzei I intend to host the site on S3 with CloudFront and HTTPS. With the trailing slash, CloudFront fails to serve the site as it couldn't route, for example, `https://www.blabla.com/about/` to `https://www.blabla.com/about/index.html` and I don't want to use ugly URLs.

**Comment by jloh** [comment]
It’s already possible to keep pretty URLs with CloudFront https://docs.aws.amazon.com/AmazonS3/latest/dev/IndexDocumentSupport.html

**Comment by ngocketit** [comment]
@jloh That wouldn't work with HTTPS I think. One workaround is maybe to use Lambda@Edge.

**Comment by jloh** [comment]
@ngocketit you put CloudFront in front of S3 for HTTPS https://aws.amazon.com/premiumsupport/knowledge-center/cloudfront-https-requests-s3/

**Comment by ngocketit** [comment]
@jloh Of course. But the problem is CloudFront doesn't allow you to use default directory indexing so that `/about/` will be mapped to `/about/index.html`. Using Lambda@Edge could solve the issue but still it'd be nice to have this feature in Hugo.

**Comment by jloh** [comment]
It does, I've done it before as have many other people https://www.davidbaumgold.com/tutorials/host-static-site-aws-s3-cloudfront/

**Comment by Mickael-van-der-Beek** [comment]
@jloh To my knowledge, the routing rules necessary to host Hugo on S3 like adding trailing slashes and using index.html as root documents means that the requests for HTML pages will always be Cloudfront misses and thus fallback to S3 that will find the find using the routing rules.

**Comment by betaveros** [comment]
Yup, I'm still here and still consider this feature essential for me to use Hugo, now for the additional lame reason that I've been hosting my site with a custom build including this feature for long enough that I would like to preserve my URLs. Even more of the tests have failed to rebase (and I really didn't even check that the ones that I did rebase are working, so I have no idea if this code works generally at all) and maybe it should be a brand new PR at this point, but I would like a signal from the core devs as to whether this feature still has a chance at being merged before proceeding.

**Comment by mutru** [comment]
URLs refer to resources, and a blog post or an about page is a great example of a resource. The trailing slash seems like a reasonable choice for improving compatibility with serving files from the file system, but for environments that support it, I'd love to have better semantics and cleaner URLs.

@bep Do you think it would be realistic to get this merged, once it's rebased and the CLA is signed?

**Comment by DandyDev** [comment]
@bep can you please merge this? I'll make another case for it that should appeal to the software engineer inside you: by forcing the use of trailing slashes because the blogpost might live inside its own directory, Hugo is leaking implementation details of the website to the end-user. **A single** blogpost, is akin to a single resource, and as such should not have a trailing slash, even if in the actual implementation the blogpost is represented by a directory with some files in it.

Compare it to an API: let's say we have an API that serves products. If I want to get a product with ID 3, I'd do: `/products/3`, even though all the information for that particular product might live in a directory with image files, CSVs and what not.

**Comment by piotrradzewicz** [comment]
Hey guys! Could you resolve conflicts and merge this PR? =) I'd really appreciate it

**Comment by DandyDev** [comment]
Calling @bep to merge this

**Comment by johnsoncodehk** [comment]
Since it has not been merged, this is a quick fix. (only change the look, not really change the url)

```html
<!-- Put in <header> or anywhere -->
<script>window.history.replaceState("", "", window.location.href.replace(new RegExp("/(?!.*/)"), ""));</script>
```

<details>
<summary>Complain</summary>
IMHO, should not let users spend so much time waiting for this basic feature. The decision to force the trailing slash is obviously causing trouble for somebody. The attitude of maintainers make me feel disheartened, so I will migrate to other builder.
</details>

**Comment by maximelouet** [comment]
I personally use a custom regex-based script in order to remove the trailing slashes. Actually, I enable the [ugly URLs](https://gohugo.io/content-management/urls/#ugly-urls) option which appends `.html` to all pages instead of slashes. Then I replace all occurences of `.html` while carefully making sure I only target my own website's links and not the external ones. I execute this script against the generated `public` directory after running `hugo`.

It works quite well but it took me a while to make it work properly. It's kinda sad such a basic feature is not implemented in Hugo; a blog post should not end with a slash as it is not a directory...

**Comment by christian-geier** [comment]
Hi! Just curious what the status is on this ? Simply cannot believe that this is not an option. Hope this will be implemented soon...

**Comment by RonPeters** [comment]
It is absolutely ridiculous that this is not yet an option. As rosell pointed out 2+ years ago, plenty of CMS'es offer this. https://discourse.gohugo.io/t/hugo-support-for-urls-without-a-trailing-slash/6763/3
All code is opinionated, but this is too much.

**Comment by virgofx** [comment]
@bep Anyway we can get a status update on this? This is very much needed!

**Comment by bep** [comment]
>@bep Anyway we can get a status update on this? This is very much needed!

I'm closing this for now. This is too big of a change for me to review/merge/maintain (I don't need this myself). We may revisit this later if/when we get more long term maintainers. This is open source: Time is limited.

**Comment by RonPeters** [comment]
In that case, I guess I will be moving on from Hugo.

**Comment by dcu** [comment]
when hosting on Cloudfront + S3, it doesn't use `index.html` for subdirectories so a common hack is copying `foo/index.html` to `foo` to simulate it... but it doesn't work with trailing slashes
is there an alternative? (different than using lambda edge which is hack as well)

**Comment by jloh** [comment]
@dcu yes, point CF at your S3 static website URL and not directly at the bucket. https://www.reddit.com/r/aws/comments/68on7h/indexhtml_in_subfolders_via_cloudfront/

**Comment by betaveros** [comment]
Sad to hear but understandable. FWIW I will probably be "maintaining" this feature by rebasing it onto my fork for as long as it's not too hard (no conflicts since when I last did this 8 months ago), with the caveat that there are basically no code tests left (doesn't seem worth it if it won't be merged; my standard for it working is "nothing breaks when I click around my blog").

**Comment by virgofx** [comment]
Just to clarify -- it does seem like 95% of the work is already done. @bep if the PR is updated with new tests would you consider merging this? (would you prefer a new PR?) It just basically allows an option as a flag.

**Comment by sdwolfz** [comment]
Just wanted to let you know that I'm also interested in this functionality, but I don't have the knowledge to take over and improve this PR :disappointed: .

**Comment by CrazyOptimist** [comment]
+1 here
I also want this func!

**Comment by sdwolfz** [comment]
So I tried adding support for this in GitLab pages a long time ago but I did not have time to work in it further, see: https://gitlab.com/gitlab-org/gitlab-pages/-/merge_requests/259 my plan was to start working on this after the former MR was merged. I might look into this in the future but my hands are tied these days. Still want this functionality though.

**Comment by Hans5958** [comment]
+1, if Jekyll does it and Netlify does it, why not Hugo?

**Comment by joaopgrassi** [comment]
@Hans5958 curious on how you said GitHub pages won't do the trailing slash? Just hosted there now and I have them.. curious on what you did?

**Comment by Hans5958** [comment]
@joaopgrassi That is just a theory. I didn't test it so don't take my word from it.

**Comment by joaopgrassi** [comment]
@Hans5958 ah ok.. well I can tell you that it does have the trailing slash on my blog hosted on gh-pages. So there's that :)

**Comment by BDHU** [comment]
Great. I was trying to move everything from Jekyll to Hugo and noticed there's this trailing slash I can't get rid of. Now the hell is let loose and it just added extra work for me to update all url. The reason I picked Hugo in the first place was so that my life would get easier, not harder...

**Pull request closed without merging**
