### PR TITLE
print error if --kind is used and cant find content type

### PR DESCRIPTION
**Pull request by hloeffler**
add error output  if `hugo new --kind` is used but can't find archetype for `--kind`
closes https://github.com/spf13/hugo/issues/3076

maybe even return error

### CODE REVIEW

**Comment by bep** [comment]
If we log an error, we should not continue. So, instead of logging an ERROR, return an error from the function.

**Comment by hloeffler** [comment]
thanks,
i also think return error is better
i can do it later, but last time it broke tests

**Comment by bep** [comment]
Not sure what the test failure is, but if you do a `rebase master` against the current Hugo, it should be fine.

**Comment by hloeffler** [comment]
failed:
https://github.com/spf13/hugo/blob/4b3ca38b2e8aa07f6fecbba0cc150b1fab9227e3/create/content_test.go#L48
easy fix, remove this line :)
more work, extend check for return values

**Comment by bep** [comment]
@hloeffler I suspect there has been too much changes in this area for this to merge cleanly, and it would probably be easier to create a new PR.

**Pull request closed without merging**
