### PR TITLE
Add genDocsHelper mage target

### PR DESCRIPTION
**Pull request by moorereason**
Expose the functionality of the hidden `hugo gen docshelper` command as
a mage target.

### CODE REVIEW

**Comment by moorereason** [comment]
See https://github.com/gohugoio/hugo/pull/7334#issuecomment-639517032

**Comment by bep** [comment]
I'm a little hesitant about this one, 3 reasons:

* It's not that much easier than doing `go run main.go gen docshelper > data.json`
* It requires us to remember to update the import path if we add more 
* I think it's enough to generate this file before every release

**Comment by moorereason** [comment]
I understand.  Some comments:

* My main motivation for this PR is to make the docshelper command more visible.  For whatever reason, my brain isn't interested in remembering the exact command, so I have to go digging for it each time.
* I'm only interested in adding a mage target.  Executing `go run` in mage is fine with me.
* I prefer to update `data.json` myself (when I remember to) instead of waiting for a release.

**Comment by bep** [comment]
Yes, with "go run" this would be good to go.

**Comment by moorereason** [comment]
Simplified to use `go run`.

**Pull request merged**
