### PR TITLE
Add a TocEntries variable to Page

### PR DESCRIPTION
**Pull request by bjchambers**
This is generated by recording the headers processed during markdown
rendering.

This allows rendering the TOC using a template rather than relying on
the built-in markdown formatted TOC.

### CODE REVIEW

**Comment by bjchambers** [comment]
I'm sure I've made a huge number of style and/or convention mistakes, since I haven't written much Go and wasn't really sure how things in hugo fit together.

I've wanted the ability to render a custom table of contents based on the headers within a document for a while, so figured I'd throw something together and see if there was any interest.

**Comment by bjchambers** [comment]
I think this change could also be useful for addressing #225 since it allows creating the actual TOC using a partial.

**Comment by bjchambers** [comment]
Some things I'm not completely sure about here:

1. How to handle dangling TOC entries (eg., skipping to a level 3 nested in a level 1). To preserve the tree-like structure, there needs to be a level entry within the level 1 that contains the level 3 entry. In the current code, this is handled by introducing a placeholder node, which allows the template to either skip the placeholders, or include just their contents, etc.

2. Representation of the TocEntry structure. Since it gets built up during rendering it needs to be mutable, but the use of the array of pointers to entries seems ugly. An alternative I considered was just doing a list-like approach, where each entry has a child pointer and a next pointer. Then rather than using `Clone` to create the template-visible value, these pointers could be traversed and turned into some easier to consume form.

3. Whether the TocEntry built during markdown rendering needs to be a tree. Another option I considered (which may be cleaner) is to just expose the list of entries reported, and then have some functions available to the templates to access those in different ways (eg., turn the list into a tree with placeholders, turn the list into a tree discarding dangling entries, etc.)

Happy to discuss these or any other considerations.

**Comment by moorereason** [comment]
Please open a thread in the `dev` section of the forums to discuss this.

**Comment by bep** [comment]
I'm sorry for this late response, but this is too big a change for what it is. I agree about the end result, but this can be done much simpler in Blackfriday.

**Pull request closed without merging**
