### PR TITLE
fix some typos

### PR DESCRIPTION
**Pull request by thirdkeyword**

### CODE REVIEW

**Comment by coliff** [comment]
@thirdkeyword heya, can you pls resolve the conflicts and see if any issues are remaining? I think they may now be all be fixed in a separate merged PR now.

**Comment by thirdkeyword** [comment]
> @thirdkeyword heya, can you pls resolve the conflicts and see if any issues are remaining? I think they may all be fixed in a separate merged PR now.

Thanks. Resolved

**Review by coliff — APPROVED** [review]

**Comment by thirdkeyword** [comment]
friendly ping~

**Comment by bep** [comment]
Thanks. For the future, please read https://github.com/gohugoio/hugo/blob/master/CONTRIBUTING.md#git-commit-message-guidelines

**Pull request merged**
