### PR TITLE
Misc Docker + Go version upgrade

### PR DESCRIPTION
**Pull request by bep**
As to the Docker image adjustments, I have tested OK:

* [x] css.TailwindCSS
* [x] PostCSS
* [x] Libsass (extended build is now default)
* [x] Dart Sass
* [x] The `hugoDocs` (Go modules, Git etc.) and misc others Go modules setups.
* [x] It sets `ENV HUGO_CACHEDIR=/cache` allowing the Hugo cache to survive builds.

On MacOS, an example build line would be:

```
docker run --rm -v .:/project -v $HOME/Library/Caches/hugo_cache:/cache imagename build
```

Starting the server:

```
docker run --rm -v .:/project -v $HOME/Library/Caches/hugo_cache:/cache imagename server --bind="0.0.0.0"
```

This is the entry point file:

```sh
#!/bin/sh

# Check if a custom hugo-docker-entrypoint.sh file exists.
if [ -f hugo-docker-entrypoint.sh ]; then
  # Execute the custom entrypoint file.
  sh hugo-docker-entrypoint.sh "$@"
  exit $?
fi

# Check if a package.json file exists.
if [ -f package.json ]; then
  # Check if node_modules exists.
  if [ ! -d node_modules ]; then
    # Install npm packages.
    # Note that we deliberately do not use `npm ci` here, as it would fail if the package-lock.json file is not up-to-date,
    # which would be the case if you run the container with a different OS or architecture than the one used to create the package-lock.json file.
    npm i
  fi
fi

exec "hugo" "$@"
```

If a custom `hugo-docker-entrypoint.sh` script exists in the root of the Hugo project, that script will be executed instead of the default entrypoint script.

### CODE REVIEW

**Comment by bep** [comment]
@jmooring I have spent some hours today trying to get up to speed re. the current Docker "scene"; I'm reasonably happy but the `Dockerfile` setup, and it should support all but 3) in your list in #12885.

I wouldn't mind if we as the next step added a `hugo-extras` (or something) with Asciidoc etc. added, but I think it would be good to have **one** base image that covered 90% of the use cases.

On my MacBook Pro M1 the image size increases from 135MB to to 406MB, which I suspect some will complain about, but it's not dramatic enough for me to even consider breaking it up into multiple setups.

What do you think? The entrypoint/npm install setup is a little opinionated, but I think it should work. I have tested it would most of my Hugo projects with a `package.json` and it seems to work fine (even with the new Tailwind). 

What do you think?

**Comment by dvdksn** [comment]
I'm taking a look at the build failure, looks like something related to cross-comp with the new Dockerfile

**Comment by dvdksn** [comment]
OK so here are some changes that I came up with;

- Currently, the `final` image is based on the `base` stage which is pinning the platform to `$BUILDPLATFORM` - we need the final image to use the target platform, so I've decoupled base and final.
  - I added a GO_VERSION arg to make sure they're both using the same golang version.
  - It seems like gcc/g++ are also runtime dependencies for libsass and libwebp, so we need to install them in both the build and final stages.
- I added clang and lld back for the C cross-compilation. I don't know too much about how this works but they're [recommended for use with xx](https://github.com/tonistiigi/xx?tab=readme-ov-file#cc)
- Re-enabled CGO
- Fixed the `install_runtimedeps_default.sh` script to use TARGETARCH instead of BUILDARCH, since we need different versions in the runtime stage.

```diff
diff --git a/Dockerfile b/Dockerfile
index 6da83a3cc..921215c59 100755
--- a/Dockerfile
+++ b/Dockerfile
@@ -2,14 +2,15 @@
 # Twitter:      https://twitter.com/gohugoio
 # Website:      https://gohugo.io/
 
+ARG GO_VERSION="1.23.2"
+
 FROM --platform=$BUILDPLATFORM tonistiigi/xx:1.5.0 AS xx
-FROM --platform=$BUILDPLATFORM golang:1.23.2-alpine AS base
-FROM base AS build
+FROM --platform=$BUILDPLATFORM golang:${GO_VERSION}-alpine AS build
 
 # Set up cross-compilation helpers
 COPY --from=xx / /
-
-# gcc/g++ are required to build libsass and libwebp libraries for the extended version.
+RUN apk add clang lld
+ARG TARGETPLATFORM
 RUN xx-apk add --no-scripts --no-cache gcc g++
 
 # Optionally set HUGO_BUILD_TAGS to "none" or "nodeploy" when building like so:
@@ -20,7 +21,7 @@ ARG HUGO_BUILD_TAGS="extended"
 ENV GOPROXY=https://proxy.golang.org
 ENV GOCACHE=/root/.cache/go-build
 ENV GOMODCACHE=/go/pkg/mod
-ARG TARGETPLATFORM
+ENV CGO_ENABLED=1
 
 WORKDIR /go/src/github.com/gohugoio/hugo
 
@@ -36,7 +37,10 @@ RUN --mount=target=. \
     xx-verify /usr/bin/hugo
 EOT
 
-FROM base AS final
+FROM golang:${GO_VERSION}-alpine AS final
+
+# libsass and libwebp also require gcc/g++ as runtime dependencies
+RUN apk add --no-scripts --no-cache gcc g++
 
 COPY --from=build /usr/bin/hugo /usr/bin/hugo
 
@@ -60,8 +64,8 @@ VOLUME /project
 WORKDIR /project
 USER hugo:hugo
 ENV HUGO_CACHEDIR=/cache
-ARG BUILDARCH
-ENV BUILDARCH=${BUILDARCH}
+ARG TARGETARCH
+ENV ARCH=${TARGETARCH/amd64/x64}
 
 COPY scripts/docker scripts/docker
 
diff --git a/scripts/docker/install_runtimedeps_default.sh b/scripts/docker/install_runtimedeps_default.sh
index 0b6c2c617..4ca88fd67 100755
--- a/scripts/docker/install_runtimedeps_default.sh
+++ b/scripts/docker/install_runtimedeps_default.sh
@@ -4,17 +4,10 @@ set -ex
 
 export DART_SASS_VERSION=1.79.3
 
-# If $BUILDARCH=arm64, then we need to install the arm64 version of Dart Sass,
-# otherwise we install the x64 version.
-ARCH="x64"
-if [ "$BUILDARCH" = "arm64" ]; then
-    ARCH="arm64"
-fi
-
 cd /tmp
 curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-${ARCH}.tar.gz 
 ls -ltr
 tar -xf dart-sass-${DART_SASS_VERSION}-linux-${ARCH}.tar.gz
 rm dart-sass-${DART_SASS_VERSION}-linux-${ARCH}.tar.gz && \
 # The dart-sass folder is added to the PATH by the caller.
-mv dart-sass /var/hugo/bin
\ No newline at end of file
+mv dart-sass /var/hugo/bin
```

**Comment by dvdksn** [comment]
I noticed you pushed some more changes, and I also noticed that the way dart-sass is installed could be improved, e.g. we install `curl` in the runtime image which isn't very good, we only want the dart-sass binary. So I made installing dart-sass a separate stage and copy the artifact from there. 

```diff
diff --git a/Dockerfile b/Dockerfile
index 6da83a3cc..4455ac8d4 100755
--- a/Dockerfile
+++ b/Dockerfile
@@ -2,14 +2,15 @@
 # Twitter:      https://twitter.com/gohugoio
 # Website:      https://gohugo.io/
 
+ARG GO_VERSION="1.23.2"
+
 FROM --platform=$BUILDPLATFORM tonistiigi/xx:1.5.0 AS xx
-FROM --platform=$BUILDPLATFORM golang:1.23.2-alpine AS base
-FROM base AS build
+FROM --platform=$BUILDPLATFORM golang:${GO_VERSION}-alpine AS build
 
 # Set up cross-compilation helpers
 COPY --from=xx / /
-
-# gcc/g++ are required to build libsass and libwebp libraries for the extended version.
+RUN apk add clang lld
+ARG TARGETPLATFORM
 RUN xx-apk add --no-scripts --no-cache gcc g++
 
 # Optionally set HUGO_BUILD_TAGS to "none" or "nodeploy" when building like so:
@@ -20,7 +21,7 @@ ARG HUGO_BUILD_TAGS="extended"
 ENV GOPROXY=https://proxy.golang.org
 ENV GOCACHE=/root/.cache/go-build
 ENV GOMODCACHE=/go/pkg/mod
-ARG TARGETPLATFORM
+ENV CGO_ENABLED=1
 
 WORKDIR /go/src/github.com/gohugoio/hugo
 
@@ -36,48 +37,57 @@ RUN --mount=target=. \
     xx-verify /usr/bin/hugo
 EOT
 
-FROM base AS final
+FROM alpine:latest AS dart-sass
+ARG TARGETARCH
+ARG ARCH=${TARGETARCH/amd64/x64}
+ARG DART_SASS_VERSION=1.79.3
+WORKDIR /tmp
+RUN apk add --no-cache curl
+RUN <<EOT
+    set -ex
+    curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-${ARCH}.tar.gz
+    tar -xf dart-sass-${DART_SASS_VERSION}-linux-${ARCH}.tar.gz
+EOT
 
-COPY --from=build /usr/bin/hugo /usr/bin/hugo
+FROM golang:${GO_VERSION}-alpine AS final
+
+# libsass and libwebp also require gcc/g++ as runtime dependencies
+RUN apk add --no-scripts --no-cache
 
 # libc6-compat & libstdc++ are required for extended libraries (libsass, libwebp).
 RUN apk add --no-cache \
+    g++ \
+    gcc \
+    git \
     libc6-compat \
     libstdc++ \
-    git \
-    runuser \
-    curl \
     nodejs \
-    npm
+    npm \
+    runuser
 
-RUN mkdir -p /var/hugo/bin && \
-    addgroup -Sg 1000 hugo && \
-    adduser -Sg hugo -u 1000 -h /var/hugo hugo && \
-    chown -R hugo: /var/hugo && \
-    runuser -u hugo -- git config --global --add safe.directory /project
+COPY --from=dart-sass /tmp/dart-sass /var/hugo/bin/dart-sass
+COPY --from=build /usr/bin/hugo /usr/bin/hugo
+ENV PATH="/var/hugo/bin:/var/hugo/bin/dart-sass:$PATH"
 
+RUN <<EOT
+    mkdir -p /var/hugo/bin /cache
+    addgroup -Sg 1000 hugo
+    adduser -Sg hugo -u 1000 -h /var/hugo hugo
+    chown -R hugo: /var/hugo /cache
+    # For the Hugo's Git integration to work.
+    runuser -u hugo -- git config --global --add safe.directory /project && \ 
+    # See https://github.com/gohugoio/hugo/issues/9810
+    runuser -u hugo -- git config --global core.quotepath false
+EOT
+
+USER hugo:hugo
 VOLUME /project
 WORKDIR /project
-USER hugo:hugo
 ENV HUGO_CACHEDIR=/cache
-ARG BUILDARCH
-ENV BUILDARCH=${BUILDARCH}
-
-COPY scripts/docker scripts/docker
-
-# Install default dependencies.
-RUN scripts/docker/install_runtimedeps_default.sh
-
-COPY scripts/docker/entrypoint.sh /entrypoint.sh
-
-ENV PATH="/var/hugo/bin:/var/hugo/bin/dart-sass:$PATH"
 
 RUN sass --version
 RUN hugo version
 
-# Expose port for live server
-EXPOSE 1313
-
+COPY scripts/docker/entrypoint.sh /entrypoint.sh
 ENTRYPOINT ["/entrypoint.sh"]
 CMD ["--help"]
-
diff --git a/scripts/docker/install_runtimedeps_default.sh b/scripts/docker/install_runtimedeps_default.sh
deleted file mode 100755
index 0b6c2c617..000000000
--- a/scripts/docker/install_runtimedeps_default.sh
+++ /dev/null
@@ -1,20 +0,0 @@
-#!/bin/sh
-
-set -ex
-
-export DART_SASS_VERSION=1.79.3
-
-# If $BUILDARCH=arm64, then we need to install the arm64 version of Dart Sass,
-# otherwise we install the x64 version.
-ARCH="x64"
-if [ "$BUILDARCH" = "arm64" ]; then
-    ARCH="arm64"
-fi
-
-cd /tmp
-curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-${ARCH}.tar.gz 
-ls -ltr
-tar -xf dart-sass-${DART_SASS_VERSION}-linux-${ARCH}.tar.gz
-rm dart-sass-${DART_SASS_VERSION}-linux-${ARCH}.tar.gz && \
-# The dart-sass folder is added to the PATH by the caller.
-mv dart-sass /var/hugo/bin
\ No newline at end of file
```

**Comment by bep** [comment]
@dvdksn thanks for the input; one of my goals of this work is to remove (at least most of) the guess work from the Docker setup (e.g. "It seems like gcc/g++ are also runtime dependencies for libsass and libwebp"; we need a libc implementation, but not the full grown compiler).

**Comment by dvdksn** [comment]
OK, then I think you can just remove

```
    g++ \
    gcc \
```

from the Dockerfile above and it should work

**Comment by bep** [comment]
OK, I guess I need to pull out my non-ARM macbook to get this up and running instead of guessing ...

**Comment by jmooring** [comment]
@bep Support for asciidoc, pandoc, and rst can wait for another day. I think this covers > 95% of use cases. I don't have any opinion on size... I suppose if someone wants something thinner they can grow their own, as many have already done.

**Pull request merged**
