### PR TITLE
Added Pandoc support.

### PR DESCRIPTION
**Pull request by zackp30**
Here is very basic Pandoc support (sorry if I didn't do it correctly, still very new to Go).

### CODE REVIEW

**Comment by bep** [comment]
@zackp30 any updates on this. This would a great addition.

**Comment by zackp30** [comment]
Sorry I've had a few exams. It is now the holidays and I shall continue this soon. Thanks for the patience.


On 3 April 2015 19:41:46 BST, "Bjørn Erik Pedersen" <notifications@github.com> wrote:
>@zackp30 any updates on this. This would a great addition.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/spf13/hugo/pull/333#issuecomment-89385871

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by priyadarshan** [comment]
This would be so helpful.

I'm sure many would be interested. For now, I have found this: http://www.personal.psu.edu/bam49/notebook/org-to-hugo/

**Comment by the-solipsist** [comment]
This would be quite welcome! Thanks for the work on this, @zackp30 !

**Pull request closed without merging**
