### PR TITLE
Fix assorted typos

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by bep** [comment]
Thanks, can you fix the commit message (see the contrib guidelines if you have any questions).

**Comment by XhmikosR** [comment]
I'm not sure how you'd like the commit message? I mean, there's no issue to reference and it's a fairly trivial patch :)

Feel free to change the message if you squash.

**Comment by bep** [comment]
>I'm not sure how you'd like the commit message? I 

As I said, we have fairly strict guidelines for commit messages in this particular repo (which GitHub just messed with its latest PR merge). 

Which is why I rather live with the typo this PR fixes than the commit message this PR produces.

You are right, I could edit the message when I squash. And I often do that, but I would much rather that the contributor gets it right him/herself, to avoid repeating the same process in the future.

**Comment by XhmikosR** [comment]
I have no problem changing the commit message. It just isn't clear to me what it should be. Right now it's "Assorted typo fixes.".

**Comment by bep** [comment]
See https://github.com/gohugoio/hugo/blob/master/CONTRIBUTING.md#git-commit-message-guidelines

> the most important part being that each commit message should have a title/subject in imperative mood starting with a capital letter and no trailing period: "Return error on wrong use of the Paginator", NOT "returning some error."

**Comment by XhmikosR** [comment]
How about "Fix assorted typos"?

**Comment by bep** [comment]
>How about "Fix assorted typos"?

Sure. Note that "Fix typos" is also perfectly fine. The main point is to remove the trailing period (".").

**Comment by XhmikosR** [comment]
Done

**Pull request merged**
