### PR TITLE
livereloadinject: Replace naive injection logic with regex

### PR DESCRIPTION
**Pull request by DominoPivot**
This PR addresses some of the concerns I raised in https://github.com/gohugoio/hugo/issues/11562. This is just a first draft and my first contribution here, do not hesitate to share thoughts.

Specifically, this PR should fix issues that arise when a document omits various combinations of html, head and body tags, which is allowed by the standard. It should also solve the bug which would cause accidental injection in a `<header>` element in place of the head.

It still won't solve problems when `<head>` is written inside comments or elements that allow arbitrary text like so:

    <title>The <head> element</title>

The current behavior of `livereloadinject` is to attempt injecting a LiveReload script after the `<head>` tag, or before the `</body>`, or after the `<html>`, or at the end of the document, whichever we can find first.

This PR changes the behavior to inject after `<head>` or `<html>` or `<!doctype>` (now truly case insensitive), or before the first `<`. This keeps the behavior more predictable instead of sometimes appending at the start, sometimes at the end.

~~I went with a single-regex approach because it's more intuitive to me and reduces code complexity quite a bit, but I understand this might come with a performance cost.~~ It indeed has a terrible cost because the regex is greedy, I will split it and force push.

I considered passing only the first 1024 bytes of the document to the regex to stop looking for the head/html/doctype beyond that point... but then I remembered my college teacher who had novels written in `<!--comments-->` at the start of every file he made. Would love a second opinion on that.

### CODE REVIEW

**Comment by DominoPivot** [comment]
I knew that greedy regex was likely very inefficient and this code would require changes, but I just realized I introduced a breaking change. Injection worked fine with this file prior to my change:

```html
<!doctype html>
<head><title>x</title></head>
...
<!-- bla bla bla <head> -->
```

All because I made the regex greedy so it would attempt to include the head instead of stopping at html or doctype. I'll fix this and write a test case so it doesn't happen again.

**Comment by DominoPivot** [comment]
I force pushed a new version that loops through a list of regular expressions to look for insertion points, closer to the original code. I added more test cases, including some of which are not covered by this solution (for example, if the string <head> was inside a comment or title).

I'll iterate on alternatives in the upcoming days.

**Comment by bep** [comment]
>I'll iterate on alternatives in the upcoming days.

@DominoPivot your implementation looks good to me, and it should be plenty fast enough for the common cases.

**Comment by bep** [comment]
... but there are some test errors.

**Comment by DominoPivot** [comment]
@bep I knew some tests would fail because they weren't solved by this approach.

I've implemented an alternative solution https://github.com/gohugoio/hugo/pull/11578 which covers all cases and more, I'll close this PR but leave the branch on my fork so we can reopen if someone can point a good reason not to go with the other one.

**Pull request closed without merging**
