### PR TITLE
build(deps): bump chroma github.com/alecthomas/chroma/v2 to v2.13.0

### PR DESCRIPTION
**Pull request by myitcv**
(see commit message)

### CODE REVIEW

**Comment by jmooring** [comment]
This would resolve https://github.com/gohugoio/hugo/issues/11862 as well.

**Comment by myitcv** [comment]
I'm happy to return to this PR to look at the build failures, but if in the meantime someone more familiar with what's failing wants to take it over that's fine with me.

**Comment by myitcv** [comment]
@jmooring - the build failures look like a genuine bug to me, and appear to have been introduced by https://github.com/alecthomas/chroma/commit/6dd9f269efaa029531b198c3c803f07dc7343c77. Thankfully the CUE change I need is the commit immediately prior to that, so I'll use that as the basis for the pseudo-version for now.

**Comment by myitcv** [comment]
@jmooring - I've force-pushed a revised commit for this PR, and raised https://github.com/alecthomas/chroma/issues/945 for what I think is a bug in chroma.

**Comment by bep** [comment]
Thanks, for future reference, please read our commit message guidelines.

**Pull request merged**
