### PR TITLE
watcher: use time.NewTicker to prevent leaks

### PR DESCRIPTION
**Pull request by alexandear**
This PR refactors `watcher.New` function to use `time.NewTicker` instead of `time.Tick`. From the [docs](https://pkg.go.dev/time#Tick):
> Tick is a convenience wrapper for NewTicker providing access to the ticking channel only. While Tick is useful for clients that have no need to shut down the Ticker, be aware that without a way to shut it down the underlying Ticker cannot be recovered by the garbage collector; it "leaks".

### CODE REVIEW

**Comment by bep** [comment]
How big of a leak are we talking about here?

**Comment by bep** [comment]
I'm merging this, but just want to note that we have 1 watcher that has the life span of a server, so it's not a ... massive leak.

**Comment by bep** [comment]
And for the future, can you try to get the commit message titles in line with the guidelines (always start with upper case).

**Comment by alexandear** [comment]
> And for the future, can you try to get the commit message titles in line with the guidelines (always start with upper case).

@bep ok. Maybe we should have a script that will force following the guideline for commit messages?

**Pull request merged**
