### PR TITLE
docs: Use img shortcode from theme

### PR DESCRIPTION
**Pull request by jmooring**

### CODE REVIEW

**Comment by bep** [comment]
Why not do this edit in the docs repo?

**Comment by jmooring** [comment]
I may not understand the process of pull/push between the docs repo and this repo. In this case, the "img" shortcode was moved from the docs repo to the theme repo a while ago. But it returned to the docs repo this morning after the merge.

**Comment by bep** [comment]
>I may not understand the process of pull/push between the docs repo and this repo.

* hugoDocs is master
* the only change going from hugo -> hugoDocs is edits done in this repo (which should be the edits that reflects new features, changes to code)
* the above looks like a bad merge situation; I try my best, but when there's a lot of merge conflicts, I may glitch.

**Comment by bep** [comment]
Just to be clear: The only motivation behind the `/docs` subtree construct is to provide a versioned snapshot of the documentation in the GitHub source tarballs (which is also why we vendor the theme).

**Comment by bep** [comment]
I'm closing this. This will eventually be synced.

**Pull request closed without merging**
