### PR TITLE
tpl: Added Google Analytics GTM (gtag.js) internal template

### LINKED ISSUE #4327: Update Google Analytics internal template to new style(gtag.js)
Hello I found Google Analytics tracing code has updated from old analytics.js to gtag.js .

Some refers:
- https://support.google.com/analytics/answer/1008080
- https://developers.google.com/analytics/devguides/collection/gtagjs/
- https://developers.google.com/analytics/devguides/collection/gtagjs/migration

Look like they are the same for basic usage. I think Hugo's Google Analytics internal template can safely update to new style.

### LINKED ISSUE #4479: Update the internal GA template
https://github.com/gohugoio/hugoDocs/blob/master/themes/gohugoioTheme/layouts/partials/gtag.html#L9

Not sure what to do with the custom dimensions above.  We could add them to site config somehow? We can probably make the `GoogleAnalytics` optionally be a map.

Also see https://discourse.gohugo.io/t/track-outbound-links-with-google-analytics/6289

### PR DESCRIPTION
**Pull request by joshgerdes**
Added an internal template that uses the new Google Tag Manager (gtag.js).
Added basic page data to be sent with the new Google Analytics call.
Added additional privacy flags to disable  google ad signals, good ad personalization signals, and sending enhanced page data to google.

Fixes #4327, Fixes #4479

### CODE REVIEW

**Comment by coliff** [comment]
Great PR. I haven't tested it, but at a glance it looks good. 👍

**Comment by davidsneighbour** [comment]
This is just a personal preference, but the whole "signal" term part in the configuration department could be left out, as it's understood by the parts left of `_signal` what they mean. At least for the hugo config part.

**Comment by AntoineSoetewey** [comment]
Hello,

Is this what we need in order to use the new Google Analytics 4 properties (https://support.google.com/analytics/answer/10089681?hl=en&utm_id=ad)?

Regards,
Antoine

**Comment by joshgerdes** [comment]
@coliff @davidsneighbour do you feel this is going to be used? If so, any changes needed? Or should I just close it?

**Comment by davidsneighbour** [comment]
I was under the impression that this was already merged. There was recently a patch for the analytics layout to work with the new shorter number format for GA4, which is only working with gtag.js, so this PR might be obsolete now. On the other hand, those privacy options are definitely not in yet and they should.

**Comment by joshgerdes** [comment]
Thanks for the reply @davidsneighbour. I might be missing it, but the only gtag reference I see in code is in a comment here:
https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/shortcodes.go#L28-L31

And there is one other related gtag PR with a `keep` label but it doesn't seem as robust as this one: https://github.com/gohugoio/hugo/pull/4208

That's great to hear that we're getting some sort of gtag update in though.

**Comment by joshgerdes** [comment]
Looks like https://github.com/gohugoio/hugo/pull/8287 was merged so should have some sort of GA4 support soon.

**Comment by djatwood** [comment]
With the merge of #8287 is this PR still necessary?

**Pull request closed without merging**
