### PR TITLE
Add render template hooks for headings

### LINKED ISSUE #6713: Support Markdown Render Hooks for Headers
A useful feature provided by many web applications is the ability to conveniently get a link referencing a specific header in the page. People can then bookmark or share the link in order to reference an individual section. Consider e.g. the [Effective Go](https://golang.org/doc/effective_go.html) page and try hovering the mouse above any of the headers with a blue background: the shown paragraph symbol is a link to the respective header. Copying the address of the link gets you the URL referencing the header.

Right now, automatically adding such anchor links is possible in Hugo by filtering the entire HTML markup of a page, e.g. given a partial `add-header-anchors.html` with

```go
{{ . | replaceRE "(<h[1-9] id=\"([^\"]+)\".+)(</h[1-9]+>)" `${1}<a href="#${2}" class="header-anchor" ariaLabel="Anchor">&para;</a>${3}` | safeHTML }}
```

One can use

```go
{{ .Content | partial "add-header-anchors" }}
```

With the advent of Markdown render hooks, this seems like a hack. Instead, it would be great if the HTML generated for headers could be customised using a hook such as `layouts/_default/_markup/render-header.html`

### PR DESCRIPTION
**Pull request by elihunter173**
This commit also

* Renames previous types to be non-specific. (e.g. hookedRenderer rather
  than linkRenderer)

Resolves #6713

This was implemented much in the same way the current hooks are implemented, pulling in method definitions from [goldmark](https://github.com/yuin/goldmark). It still needs testing and documentation, but on my personal website I was able to successfully replace the `replaceRE` partial hack described in the issue above with a `render-heading.html` template similar to the one described.

### CODE REVIEW

**Comment by apexskier** [comment]
Hey, I've got a PR ready that adds a test for this feature at https://github.com/elihunter173/hugo/pull/1.

Also, I've got PRs for documentation (https://github.com/gohugoio/hugoDocs/pull/1100) and to use the new feature in the Hugo website theme (https://github.com/gohugoio/gohugoioTheme/pull/146). I'm not entirely sure on the contribution process for docs and the theme though - there are scripts here to update them from those other repos, but I'm not sure how consistently they're being used.

**Comment by elihunter173** [comment]
Thanks @apexskier!

I've been stalling on this PR because of university which luckily recently wrapped up. I plan to add comments and tests in the next week hopefully. Maybe two.

**Comment by apexskier** [comment]
@elihunter173 If you can get my PR merged into your branch, we can potentially get this merged in sooner! Since it's a PR to a fork, it's not going to get attention by the broader hugo community as is.

**Comment by bep** [comment]
@elihunter173 @apexskier the code looks great ... I thought some time about one of the name changes, but I didn't come up with something better, so I think this is good to go. If you give me thumbs up, I'll merge -- and I can cherry-pick @apexskier 's test commit as a separate thing. Feel free to follow-up with comments etc. in a future PR.

**Comment by elihunter173** [comment]
@bep Ah, I merged @apexsier's PR onto my fork (simple 1-commit rebase) before I saw your message. I can remove it from this PR if you'd like so you can merge his test commit separately.

As for the comments, I might in a separate PR. I just reviewed the code again and it was in a much better state than I remember, so I'm happy with this being merged. Removing "WIP" from the title.

**Comment by bep** [comment]
Great job, much appreciated. @apexskier I have noted the docs/theme changes once we release, but please remind me if I ... forget.

**Pull request merged**
