### PR TITLE
Fix tab selection of disabled items in internal pagination template

### LINKED ISSUE #8715: Tab-selecting disabled pagination navigation items
The internal template for pagination generates navigation elements that are tab-selectable in disabled state.

BTW: This seems to be a regression since Hugo 0.80

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.84.0-2C4689F7B linux/amd64 BuildDate=2021-06-18T17:14:27Z VendorInfo=gohugoio
</pre>

### PR DESCRIPTION
**Pull request by raoulb**
Fixes #8715

### CODE REVIEW

**Review by jmooring — CHANGES_REQUESTED** [review]
Run tests with `mage -v check`. It will fail.
You also need to update:
<https://github.com/gohugoio/hugo/blob/master/hugolib/embedded_templates_test.go#L155>

**Comment by jmooring** [comment]
Please run `mage -v check`. The test still fails. You need to run tests locally before submitting PRs.

**Review by jmooring — APPROVED** [review]

**Comment by jmooring** [comment]
@raoulb

When you ran `mage generate` before testing locally, it updated `tpl/tplimpl/embedded/templates.autogen.go`. You need to commit this change as well. When I update embedded templates...

```
mage generate
go install -tags extended
mage -v check
```

**Comment by raoulb** [comment]
Thanks for the explanation. I did not have a go development setup at hand.

**Pull request merged**
