### PR TITLE
tplimpl: Added shortcode for cloaking email

### LINKED ISSUE #3886: Cloak e-mail
Feature request: cloak email.

Take an email address like example@mail.com. If that was to appear on one of your posts/pages, it could easily be ‘scraped’ or ‘harvested’ automatically to add that email address to a spam list of some sort. Cloaking is all about making that harder to do.

[Joomla!](https://docs.joomla.org/How_to_cloak_email_addresses), [WordPress](https://wordpress.org/plugins/email-javascript-cloaker/) and other popular CMS provides feature named "cloak email". It cause replace any `<a href="mailto:example@mail.com">mailto:example@mail.com</a>` to uglified JavaScript which generate original mailto link after webpage was loaded in browser.

Proposal: implement build-in shortcode for it. It must be implemented in Go because uglify function is should not be trivial.

### PR DESCRIPTION
**Pull request by danieka**
Fixes #3886

### CODE REVIEW

**Comment by danieka** [comment]
Looking at the PR now that I've submitted it I see that the code's readability is subpar. Should I split the shortcode output on multiple lines?

**Comment by danieka** [comment]
Hi guys/gals,

I know this PR may be difficult to review and it's not obvious that this is a good solution. But let me know if there's anything I can do to make your job of reviewing it easier. You should also feel free to close the PR if you don't think this is a good fit for Hugo. I won't mind 😄

**Comment by bep** [comment]
@danieka sorry for not getting back to you sooner on this. This PR looks good, but I think this falls a little outside of the scope of what in the Hugo core. We are working on making it easier to "share shortcodes" as components, and the next Hugo version (tomorrow) will be a step in that direction.

Again, thanks for this contribution, but I feel that this has to wait.

**Comment by RealOrangeOne** [comment]
@danieka may be of interest to you https://discourse.gohugo.io/t/hugo-theme-utils/12376

**Comment by danieka** [comment]
@RealOrangeOne interesting, I'll make a PR to your repo as soon as I have some free time

**Comment by danieka** [comment]
@bep No problem 😄 I totally get, and agree, with your point.

**Pull request closed without merging**
