### PR TITLE
Generate custom error pages

### LINKED ISSUE #5066: Generate custom error pages
Referencing [https://discourse.gohugo.io/t/how-to-create-custom-error-pages/755](https://discourse.gohugo.io/t/how-to-create-custom-error-pages/755)

It would be nice if Hugo could generate custom error pages. Not only for 404 errors. It could use a regex like `/\d{3}.html/` for pages in `/layouts/`.

### PR DESCRIPTION
**Pull request by satotake**
Render layouts/(4xx|5xx).html
resolves #5066

### CODE REVIEW

**Comment by bep** [comment]
Thanks for this.

I find it a little bit odd that this is restricted to HTML, which is the format where I would least expect a 403 etc. to be useful ...?

**Comment by satotake** [comment]
Thank you

Probably I miss your point but I assume that they are always HTML.
For example, these error pages are used for [CloudFront's error pages](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValuesErrorPages)
Could you describe more details?

**Comment by bep** [comment]
>Probably I miss your point but I assume that they are always HTML.

I have never seen a 400 or 500 error for a static Hugo site. I could however maybe these error endpoints being used by some JSON service, not sure.

For HTML I guess 403's could happen.

**Comment by satotake** [comment]
> I have never seen a 400 or 500 error for a static Hugo site. 

This is true when we use Hugo and static site hosting service (such as [Netlify](https://www.netlify.com/)).
Instead, these error pages are generated in cases where Hugo is combined with a front server.
For example, Nginx for the purpose of auth or proxy. 
These cases can raise 500 etc and have the chance to serve customized error pages.
The use cases may be minor, I mean, out of Hugo's scope. 
If so, I will close this PR.

**Pull request closed without merging**
