### PR TITLE
Support offline builds

### PR DESCRIPTION
**Pull request by vassudanagunta**
Currently Hugo's mage build targets depend on the Vendor target, meaning that `go get -u github.com/golang/dep/cmd/dep` is executed each and every time. Not only does this unnecessarily slow builds, it prevents builds when one's machine is offline (no internet access). 

Since Mage now supports invoking multiple build targets, there is no longer a need to hardcode the dependency on the Vendor target. For example:

- offline build: `mage Hugo`
- online build, with updated dependencies: `mage Vendor Hugo`

### CODE REVIEW

**Comment by bep** [comment]
Thanks for this. A couple of things:

* Remove the console prints. They were not there originally for a reason, and they're not relevant to this issue.
* Get your commit message(s) in line with the rest

But most importantly:

* Is all use of `mage` in this repo updated to handle the new build targets?

**Comment by vassudanagunta** [comment]
@bep 

I did an exhaustive search for all mage calls and got everything I could find. I just checked again and it doesn't look like I missed anything, though i went ahead and merge two mage calls in `smapcraft.yaml` for consistency. 

I removed the console prints. 

I also updated CONTRIBUTING.md to take advantage of the mage targets and simplify it some. I can simplify it more, but I'll do that in a separate pull request when I get the chance.

**Comment by bep** [comment]
Good. I will probably have to do one more patch release for 0.32 (later today), and prefer to do that from master if I can. So I will merge this after.

**Comment by vassudanagunta** [comment]
@bep README.md

```
To update Hugo’s dependencies, use `go get` with the `-u` option.

    go get -u -v github.com/gohugoio/hugo
```

**Comment by vassudanagunta** [comment]
@bep 

README.md currently says:
```
To update Hugo’s dependencies, use `go get` with the `-u` option.

    go get -u -v github.com/gohugoio/hugo
```

This seems to contradict CONTRIBUTING.md (both before and after the changes in this pull request). Will the above still "build and install the binaries" as the README.md says, or will users have to install and run Mage as CONTRIBUTING.md says? If the latter, I will update the README.

**Comment by vassudanagunta** [comment]
@bep ping... I think you missed my last message above, re README.md...

**Pull request merged**
