### PR TITLE
Remove .Site.Authors from embedded templates

### LINKED ISSUE #4458: References to .Site.Authors need to be cleaned up?
Hello,

I had opened up https://discourse.gohugo.io/t/site-authors-not-implemented/10446 on Discourse for discussion, but haven't received any feedback.

The gist of the problem is that internal templates like `twitter_cards` and `opengraph` reference `.Site.Authors`, but no matter what I do, those variables do not get set.

While diving through the Hugo source code through my Go-unexperienced eyes, I realized that those variables are "declared" but never "assigned" (*not sure what the correct Go-lingo is for that*).

You can read the above linked Discourse thread for details and code snippet references.

### PR DESCRIPTION
**Pull request by jmooring**
Closes #4458

### CODE REVIEW

**Comment by jmooring** [comment]
This came up again this morning:
<https://discourse.gohugo.io/t/opengraph-template-help/32613>

Please merge or provide feedback. Thanks.

**Comment by cryptic-code** [comment]
`article:author`, `article:publisher` and `twitter:creator` meta tags totally removed from the social media templates?

They need to be there. Why not only remove their dependency on `.Site.Authors` variable?

**Comment by jmooring** [comment]
@cryptic-code, Thank you for sharing your concerns on this. Here are my thoughts:

1. We didn't remove anything, because none of it was rendered... ever. 
2. It is trivial for site creators to copy and customize the embedded templates as needed.
3. There's an open issue to define an authors data model: https://github.com/gohugoio/hugo/issues/3088. Perhaps when this is settled we can revisit these embedded templates.

If you have questions about how to copy and customize an embedded template, please create a topic on the forum (https://discourse.gohugo.io/). Thanks.

**Comment by cryptic-code** [comment]
> @cryptic-code, Thank you for sharing your concerns on this. Here are my thoughts:
> 
> 1. We didn't remove anything, because none of it was rendered... ever.
> 2. It is trivial for site creators to copy and customize the embedded templates as needed.
> 3. There's an open issue to define an authors data model: #3088. Perhaps when this is settled we can revisit these embedded templates.
> 
> If you have questions about how to copy and customize an embedded template, please create a topic on the forum (https://discourse.gohugo.io/). Thanks.

@jmooring Yes. I'm aware that the tags were never rendered and that they are not critical for any site feature.

I raised the concern since having them is still recommended.

I have already customized my template accordingly.

Anyways, thanks. `.Site.Authors` caused a lot of confusion for beginners (including me).

**Pull request merged**
