### PR TITLE
all: Fix pkg is being imported more than once

### PR DESCRIPTION
**Pull request by testwill**

### CODE REVIEW

**Comment by bep** [comment]
Thanks for this. 

Can you fix the commit message to be in line with the guidelines?

**Comment by bep** [comment]
https://github.com/gohugoio/hugo/blob/master/CONTRIBUTING.md#git-commit-message-guidelines

**Comment by testwill** [comment]
ok, thanks

**Comment by bep** [comment]
Also, it's the _commit message title_ that's relevant, not the PR title.

**Comment by testwill** [comment]
ok, thanks

**Comment by alexandear** [comment]
I did the fix in #10797

**Pull request closed without merging**
