### PR TITLE
Reuse frontmatter parser in classifier

### PR DESCRIPTION
**Pull request by evankanderson**
While looking at #4691 , I noticed that the code in `classifier.go` does some ad-hoc parsing for HTML vs other content.

Given that a page without frontmatter can't be usefully parsed, it seemed more straightforward to reuse the frontmatter parser to determine whether the HTML file was content or a plain file.

Unfortunately, it turns out that TestSectionNaming has some HTML documents that are just strings without frontmatter, so I ended up needing to adjust those tests.

I'm wondering whether it makes sense to apply this "has frontmatter" test universally in ClassifyContentFile; it appears that doing so would need updates in the following tests from hugolib:

    TestCascade
    TestContentMap
    TestRenderStringOnListPage
    TestSiteBuildErrors
    TestShortCodesInSite
    TestSectionNaming
    TestRefLinking
    TestCrossrefs
    TestDataFromShortcode

### CODE REVIEW

**Comment by bep** [comment]
Thanks for this, and while I  agree that this in general looks like a good thing, one quick note: The reason I implemented this buffered "quick detector" for pure HTML files was to avoid having to read the entire file into memory.

We have some benchmarks that usually shows these issues named "BenchmarkSiteNew/*" (or something).

One tip would to have a look at this tool: https://github.com/bep/gobench

Not much documentation, but look at the `hugobench -h` output.

**Comment by bep** [comment]
Note that I don't think we use HTML files in the above mentioned benchmarks, though.

**Comment by bep** [comment]
Or, as it is for HTML only, maybe it doesn't matter too much the memory overhead...

**Comment by evankanderson** [comment]
I changed BenchmarkSiteNew to use HTML files for most of the content instead of markdown.

The result is around a 8% increase in allocations and somewhere between 1% and 17% on CPU time (17% for "edit" case, 1% for "regular" case).

I can work on splitting `ParseFrontMatterAndContent` into a `ParseFrontMatter` which reads from the file more carefully until `Iterator.Input()` is called.

I'm also in the process of rerunning the benchmark to see if I can get more stable results; I suspect I'm thermal throttling on my laptop so I may have to switch to another machine.

```
 go version go1.13.5 darwin/amd64

goos: darwin
goarch: amd64
pkg: github.com/gohugoio/hugo/hugolib
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      30	  42251521 ns/op	26922799 B/op	  255512 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      33	  34802199 ns/op	26947088 B/op	  255513 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      34	  34643581 ns/op	26916856 B/op	  255498 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      32	  33918035 ns/op	26933820 B/op	  255511 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      22	  48963396 ns/op	32867477 B/op	  320103 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      22	  50271350 ns/op	32937488 B/op	  320113 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      22	  51166796 ns/op	32900642 B/op	  320124 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      22	  61399388 ns/op	32884646 B/op	  320115 allocs/op
PASS
ok  	github.com/gohugoio/hugo/hugolib	21.834s
Switched to branch 'classier'
Your branch and 'upstream/master' have diverged,
and have 3 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)


 go version go1.13.5 darwin/amd64

goos: darwin
goarch: amd64
pkg: github.com/gohugoio/hugo/hugolib
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      22	  48980276 ns/op	28580883 B/op	  275674 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      28	  38236375 ns/op	28590353 B/op	  275676 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      30	  40761404 ns/op	28575465 B/op	  275661 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      31	  39999467 ns/op	28566667 B/op	  275663 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      20	  54808500 ns/op	34561612 B/op	  340271 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      20	  54804296 ns/op	34575206 B/op	  340281 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      19	  55202866 ns/op	34568818 B/op	  340272 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      20	  54575961 ns/op	34559677 B/op	  340273 allocs/op
PASS
ok  	github.com/gohugoio/hugo/hugolib	17.227s


name                                 old time/op    new time/op    delta
SiteNew/Edit_Deep_content_tree-8       36.4ms ±16%    42.0ms ±17%    ~     (p=0.200 n=4+4)
SiteNew/Regular_Deep_content_tree-8    53.0ms ±16%    54.8ms ± 1%    ~     (p=0.343 n=4+4)

name                                 old alloc/op   new alloc/op   delta
SiteNew/Edit_Deep_content_tree-8       26.9MB ± 0%    28.6MB ± 0%  +6.12%  (p=0.029 n=4+4)
SiteNew/Regular_Deep_content_tree-8    32.9MB ± 0%    34.6MB ± 0%  +5.07%  (p=0.029 n=4+4)

name                                 old allocs/op  new allocs/op  delta
SiteNew/Edit_Deep_content_tree-8         256k ± 0%      276k ± 0%  +7.89%  (p=0.029 n=4+4)
SiteNew/Regular_Deep_content_tree-8      320k ± 0%      340k ± 0%  +6.30%  (p=0.029 n=4+4)
```

**Comment by evankanderson** [comment]
Here are --count=10 results, which show around a 6% increase in CPU time for the "edit" case and 0% for the "regular" case, along with the same memory allocation deltas as before.

```
Benchmark and compare branch "clean" and "classier".
Switched to branch 'clean'
Your branch and 'upstream/master' have diverged,
and have 1 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)


 go version go1.13.5 darwin/amd64

goos: darwin
goarch: amd64
pkg: github.com/gohugoio/hugo/hugolib
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      31	  38821229 ns/op	26933989 B/op	  255510 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      31	  34190873 ns/op	26924626 B/op	  255505 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      27	  37272635 ns/op	26933585 B/op	  255508 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      32	  36690488 ns/op	26936151 B/op	  255506 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      32	  36147433 ns/op	26927754 B/op	  255517 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      30	  37170453 ns/op	26934790 B/op	  255517 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      32	  36515062 ns/op	26930886 B/op	  255515 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      32	  39681874 ns/op	26935943 B/op	  255515 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      31	  40256163 ns/op	26929189 B/op	  255510 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      31	  42475208 ns/op	26937511 B/op	  255514 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      22	  51928399 ns/op	32880291 B/op	  320115 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      22	  59874902 ns/op	32886961 B/op	  320116 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      22	  53097418 ns/op	32931261 B/op	  320117 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      20	  58198183 ns/op	32929927 B/op	  320119 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      19	  60903281 ns/op	32950847 B/op	  320113 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      21	  52178128 ns/op	32950346 B/op	  320115 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      21	  54204179 ns/op	32889567 B/op	  320099 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      22	  54095487 ns/op	32922389 B/op	  320122 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      21	  54844351 ns/op	32923675 B/op	  320120 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      22	  52709922 ns/op	32961530 B/op	  320119 allocs/op
PASS
ok  	github.com/gohugoio/hugo/hugolib	53.162s
Switched to branch 'classier'
Your branch and 'upstream/master' have diverged,
and have 3 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)


 go version go1.13.5 darwin/amd64

goos: darwin
goarch: amd64
pkg: github.com/gohugoio/hugo/hugolib
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      26	  40784890 ns/op	28583137 B/op	  275675 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      33	  40689480 ns/op	28577316 B/op	  275674 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      31	  42765048 ns/op	28566673 B/op	  275664 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      28	  40516672 ns/op	28575105 B/op	  275666 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      28	  39034358 ns/op	28574294 B/op	  275664 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      25	  40743277 ns/op	28570709 B/op	  275675 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      26	  40784004 ns/op	28589587 B/op	  275674 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      27	  38129513 ns/op	28566417 B/op	  275663 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      30	  42182210 ns/op	28573935 B/op	  275665 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      28	  38228966 ns/op	28592859 B/op	  275670 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      21	  54590331 ns/op	34566702 B/op	  340271 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      20	  54788696 ns/op	34591464 B/op	  340278 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      19	  55449936 ns/op	34562114 B/op	  340279 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      20	  58160737 ns/op	34541733 B/op	  340265 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      19	  57530338 ns/op	34624665 B/op	  340277 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      20	  54563267 ns/op	34647628 B/op	  340284 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      20	  52997614 ns/op	34585548 B/op	  340276 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      19	  54799260 ns/op	34552685 B/op	  340272 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      19	  57230261 ns/op	34590016 B/op	  340271 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      19	  57058014 ns/op	34571560 B/op	  340278 allocs/op
PASS
ok  	github.com/gohugoio/hugo/hugolib	43.979s


name                                 old time/op    new time/op    delta
SiteNew/Edit_Deep_content_tree-8       37.9ms ±12%    40.4ms ± 6%  +6.50%  (p=0.011 n=10+10)
SiteNew/Regular_Deep_content_tree-8    55.2ms ±10%    55.7ms ± 5%    ~     (p=0.393 n=10+10)

name                                 old alloc/op   new alloc/op   delta
SiteNew/Edit_Deep_content_tree-8       26.9MB ± 0%    28.6MB ± 0%  +6.11%  (p=0.000 n=10+10)
SiteNew/Regular_Deep_content_tree-8    32.9MB ± 0%    34.6MB ± 0%  +5.02%  (p=0.000 n=10+9)

name                                 old allocs/op  new allocs/op  delta
SiteNew/Edit_Deep_content_tree-8         256k ± 0%      276k ± 0%  +7.89%  (p=0.000 n=10+10)
SiteNew/Regular_Deep_content_tree-8      320k ± 0%      340k ± 0%  +6.30%  (p=0.000 n=9+10)
```

**Comment by evankanderson** [comment]
FWIW, applying the frontmatter check to all files leads to similar build times and +8%-9% allocations.

**Comment by bep** [comment]
> I suspect I'm thermal throttling on my laptop so I may have to switch to another machine.

Not sure what OS you are on, but my golden tip on MacOS is to install Turbo Boost Switcher -- and turn that off when running benchmarks.

My instinct tells me that:

* For sites that use mostly HTML content files (with front matter), the penalty here will be significant. I think you need to increase the HTML file size in the benchmarks to make it more real.
* A fix would be to somehow make the parser buffered, but that would mean a rewrite, which I'm not sure is the topic of this particular issue.

**Comment by evankanderson** [comment]
Trying again with larger HTML does reveal a 10-15% difference in CPU time with much larger HTML files (which is probably more realistic -- see https://github.com/gohugoio/hugo/pull/7088/commits/95b9ef9b510ecb3668362ade97cd00e4313e84a4 and https://github.com/gohugoio/hugo/pull/7088/commits/9c034df72f83eccda3979b8f94527fd258424737 for the changes.

Would you like me to commit at least https://github.com/gohugoio/hugo/pull/7088/commits/95b9ef9b510ecb3668362ade97cd00e4313e84a4 (separately) to have HTML files in the benchmark?

```
$ gobench -package=./hugolib -bench="BenchmarkSiteNew/Deep_content_tree" -base clean -count 10
Benchmark and compare branch "clean" and "classier".
Switched to branch 'clean'
Your branch and 'upstream/master' have diverged,
and have 2 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)


 go version go1.13.5 darwin/amd64

goos: darwin
goarch: amd64
pkg: github.com/gohugoio/hugo/hugolib
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      14	  98541868 ns/op	50233599 B/op	  349514 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      15	  74769839 ns/op	50239447 B/op	  349495 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      14	  78039988 ns/op	50231674 B/op	  349492 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      14	  79725531 ns/op	50256285 B/op	  349498 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      15	  70621619 ns/op	50208484 B/op	  349505 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      16	  78064357 ns/op	50231592 B/op	  349487 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      18	  82328296 ns/op	50194910 B/op	  349490 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      14	  80069058 ns/op	50248842 B/op	  349496 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      14	  73815900 ns/op	50216518 B/op	  349504 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      14	  81175073 ns/op	50241414 B/op	  349500 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      12	  98702417 ns/op	64321724 B/op	  415436 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      12	  93257931 ns/op	64351320 B/op	  415418 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      12	  96247710 ns/op	64340197 B/op	  415418 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      12	  91141394 ns/op	64289131 B/op	  415409 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      12	  92614521 ns/op	64348725 B/op	  415436 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      12	  93837764 ns/op	64306518 B/op	  415414 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      12	  95883651 ns/op	64349421 B/op	  415415 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      12	  96928766 ns/op	64345728 B/op	  415432 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      12	  92704936 ns/op	64307549 B/op	  415431 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      12	  90979902 ns/op	64307488 B/op	  415427 allocs/op
PASS
ok  	github.com/gohugoio/hugo/hugolib	57.664s
Switched to branch 'classier'
Your branch and 'upstream/master' have diverged,
and have 4 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)


 go version go1.13.5 darwin/amd64

goos: darwin
goarch: amd64
pkg: github.com/gohugoio/hugo/hugolib
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      12	 100225984 ns/op	62714252 B/op	  384514 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      14	  83270607 ns/op	62709312 B/op	  384496 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      13	  80275202 ns/op	62742745 B/op	  384495 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      13	  90625646 ns/op	62719070 B/op	  384504 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      13	  83803064 ns/op	62704004 B/op	  384490 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      13	  79374122 ns/op	62756000 B/op	  384498 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      13	  77768385 ns/op	62738168 B/op	  384486 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      13	  83671371 ns/op	62784828 B/op	  384504 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      13	  90531701 ns/op	62752741 B/op	  384479 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      12	  84060268 ns/op	62723508 B/op	  384494 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      10	 110616452 ns/op	76831396 B/op	  450431 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      10	 109269633 ns/op	76868226 B/op	  450432 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      10	 105963661 ns/op	76884440 B/op	  450451 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      10	 104363979 ns/op	76863216 B/op	  450428 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      10	 105875770 ns/op	76948133 B/op	  450449 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      10	 110638124 ns/op	76927885 B/op	  450446 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      10	 110512414 ns/op	76875922 B/op	  450448 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      10	 108193378 ns/op	76869274 B/op	  450440 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      10	 105768744 ns/op	76926130 B/op	  450438 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	       9	 113038536 ns/op	76943137 B/op	  450433 allocs/op
PASS
ok  	github.com/gohugoio/hugo/hugolib	49.239s


name                                 old time/op    new time/op    delta
SiteNew/Edit_Deep_content_tree-8       77.6ms ± 9%    85.4ms ±17%   +9.97%  (p=0.006 n=9+10)
SiteNew/Regular_Deep_content_tree-8    94.2ms ± 5%   108.4ms ± 4%  +15.06%  (p=0.000 n=10+10)

name                                 old alloc/op   new alloc/op   delta
SiteNew/Edit_Deep_content_tree-8       50.2MB ± 0%    62.7MB ± 0%  +24.89%  (p=0.000 n=10+10)
SiteNew/Regular_Deep_content_tree-8    64.3MB ± 0%    76.9MB ± 0%  +19.54%  (p=0.000 n=10+10)

name                                 old allocs/op  new allocs/op  delta
SiteNew/Edit_Deep_content_tree-8         349k ± 0%      384k ± 0%  +10.01%  (p=0.000 n=10+10)
SiteNew/Regular_Deep_content_tree-8      415k ± 0%      450k ± 0%   +8.43%  (p=0.000 n=10+10)
```

**Comment by bep** [comment]
image

It isn't so much the runtime that is the problem in this case, but the memory allocation:

image

The numbers above aren't surprising, but we need a pretty good reason to go with this -- even if it is only for a small sub set of Hugo sites out there.

**Comment by evankanderson** [comment]
I've been able to reduce the allocated memory substantially by pre-allocating the buffer in `parseSection` rather than using `ioutil.ReadAll`, which uses bytes.Buffer with no pre-allocation. (Note that bytes.Buffer will always `.grow()` at least once, even if it's big enough to read the entire content.)

I see wild variations in CPU time such that I don't actually believe the `p` values from benchstat. Here's one run, however:

```
Benchmark and compare branch "clean" and "classier".
Switched to branch 'clean'
Your branch and 'upstream/master' have diverged,
and have 2 and 2 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)


 go version go1.13.5 darwin/amd64

goos: darwin
goarch: amd64
pkg: github.com/gohugoio/hugo/hugolib
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      13	 100847547 ns/op	50265277 B/op	  349512 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      14	  92521729 ns/op	50222924 B/op	  349510 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      15	  78965677 ns/op	50234167 B/op	  349495 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      13	  83444301 ns/op	50283592 B/op	  349504 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      13	  90895748 ns/op	50245435 B/op	  349507 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      14	  84128448 ns/op	50231322 B/op	  349500 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      12	 102142978 ns/op	64275498 B/op	  415423 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      12	  95517969 ns/op	64341695 B/op	  415428 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      12	  95692548 ns/op	64315472 B/op	  415414 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      12	  95604914 ns/op	64327500 B/op	  415433 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      12	  99251895 ns/op	64296370 B/op	  415431 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      12	  95493381 ns/op	64326314 B/op	  415423 allocs/op
PASS
ok  	github.com/gohugoio/hugo/hugolib	27.832s
Switched to branch 'classier'
Your branch and 'upstream/master' have diverged,
and have 6 and 2 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)


 go version go1.13.5 darwin/amd64

goos: darwin
goarch: amd64
pkg: github.com/gohugoio/hugo/hugolib
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      12	  94980863 ns/op	48415918 B/op	  380248 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      13	  95400138 ns/op	48399095 B/op	  380235 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      14	  85350863 ns/op	48437783 B/op	  380223 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      13	  81347619 ns/op	48405072 B/op	  380207 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      13	  94719896 ns/op	48387639 B/op	  380232 allocs/op
BenchmarkSiteNew/Edit_Deep_content_tree-8         	      14	  81889018 ns/op	48379697 B/op	  380222 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      10	 106359458 ns/op	62547449 B/op	  446151 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      10	 104374082 ns/op	62510941 B/op	  446160 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      10	 102857217 ns/op	62530656 B/op	  446160 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      10	 107853963 ns/op	62538294 B/op	  446142 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      10	 104632485 ns/op	62526080 B/op	  446152 allocs/op
BenchmarkSiteNew/Regular_Deep_content_tree-8      	      10	 109770034 ns/op	62582497 B/op	  446153 allocs/op
PASS
ok  	github.com/gohugoio/hugo/hugolib	29.433s


name                                 old time/op    new time/op    delta
SiteNew/Edit_Deep_content_tree-8       88.5ms ±14%    88.9ms ± 9%    ~     (p=0.818 n=6+6)
SiteNew/Regular_Deep_content_tree-8    97.3ms ± 5%   106.0ms ± 4%  +8.93%  (p=0.002 n=6+6)

name                                 old alloc/op   new alloc/op   delta
SiteNew/Edit_Deep_content_tree-8       50.2MB ± 0%    48.4MB ± 0%  -3.67%  (p=0.002 n=6+6)
SiteNew/Regular_Deep_content_tree-8    64.3MB ± 0%    62.5MB ± 0%  -2.76%  (p=0.002 n=6+6)

name                                 old allocs/op  new allocs/op  delta
SiteNew/Edit_Deep_content_tree-8         350k ± 0%      380k ± 0%  +8.79%  (p=0.002 n=6+6)
SiteNew/Regular_Deep_content_tree-8      415k ± 0%      446k ± 0%  +7.40%  (p=0.002 n=6+6)
```

**Comment by evankanderson** [comment]
I also played around a bit with converting the lexer to perform partial parsing by replacing `run` with a `step` method and calling it appropriately in pageparser, along with a method to simply read the FrontMatter. Unfortunately, that didn't seem to have any effect on outcomes.

**Comment by evankanderson** [comment]
Playing around a bit more with single-step and 10-step lexing vs running everything in a batch, it appears that (at least on my Mac with turbo boost disabled), there's too much noise in the CPU time to make much of a statement about impact, surprisingly:

Results for `go test -run=NONE -bench BenchmarkSiteNew/Deep_content_tree -test.benchmem=true ./hugolib -count 6 -benchtime=10s` across 4 branches:

* Head with 95b9ef9 and 4adb172 ("clean")
* This PR
* This PR plus adding `pageparser.ParseFrontMatter` with an incremental `pageLexer.step` method
* The `ParseFrontMatter` PR with a batch size of 10 on `pageLexer.step`

```
name \ time/op                       clean        PR           FrontMatter  FrontMatter-batch10
SiteNew/Edit_Deep_content_tree-8      126ms ±11%   111ms ±22%   118ms ±15%           120ms ±26%
SiteNew/Regular_Deep_content_tree-8   121ms ±25%   114ms ± 8%   128ms ±23%           118ms ±15%

name \ alloc/op                      clean        PR           FrontMatter  FrontMatter-batch10
SiteNew/Edit_Deep_content_tree-8     50.2MB ± 0%  48.3MB ± 0%  48.3MB ± 0%          48.3MB ± 0%
SiteNew/Regular_Deep_content_tree-8  64.1MB ± 0%  62.3MB ± 0%  62.3MB ± 0%          62.3MB ± 0%

name \ allocs/op                     clean        PR           FrontMatter  FrontMatter-batch10
SiteNew/Edit_Deep_content_tree-8       349k ± 0%    380k ± 0%    380k ± 0%            380k ± 0%
SiteNew/Regular_Deep_content_tree-8    415k ± 0%    446k ± 0%    446k ± 0%            446k ± 0%
```

I'm a bit surprised at the variance in execution time, but it's been consistent on all my testing.

**Comment by evankanderson** [comment]
Note that according to the above benchmarks, this is now -3% memory allocated, though +8% allocation calls, and the time delta is within the (broad) error bounds.

**Comment by evankanderson** [comment]
@bep 

Should I abandon this, including the -3% memory usage? Should I do just the memory usage change?

In working on #4691, I discovered that I need to check non-HTML files for frontmatter as well. My current (working) tree re-uses the frontmatter parser here, which would be my preference, but I can implement a simplified frontmatter checker for other formats as well if that would be your preference.

**Pull request closed without merging**
