### PR TITLE
tpl: Add functions for hex encoding and secretbox encryption

### PR DESCRIPTION
**Pull request by moorereason**
Add a new hexEncode and hexDecode to the encoding namespace.

Add a new secretbox namespace (under crypto) for nacl secretbox
operations, Seal and Open.

Updates #7547

### CODE REVIEW

**Comment by moorereason** [comment]
@bep, let me know what you think of this.  I'm not a cryptographer (no surprise there!), but NaCl was made to be easy and full-proof.

**Comment by bep** [comment]
> easy and full-proof.

Was that typo intentional?

I think we need to demonstrate "usefulness" here before we add this. The only type of bugs I'm worried about here is what we've seen in Outlook (I think) where they have for some odd reason sent encrypted messages as plain text. 

"We have test", you say.

Yes, but I have seen stranger things happen where people comment out code paths and tests to debug something, then forgets to enable it ...

**Comment by moorereason** [comment]
> Was that typo intentional?

Sort of.  The whole point of NaCl is to not be a footgun.  It's about as easy as crypto can get, and it's about the max level of complexity I'm willing consider exposing in Hugo.

Usefulness discussions are in the original issue.

Part of my desire to create this PR was to see what the implementation would look like.  What sharp edges are there?  Can I make a sub-package under crypto and import it into the template func namespace?

I share your concern with user mistakes, however, I don't know how to defend against that.  Any ideas?  I assume you mean site creators not Hugo developers.

**Comment by bep** [comment]
>I assume you mean site creators not Hugo developers.

No, I mean you and me.

**Pull request closed without merging**
