### PR TITLE
Added support for multiple config files via --config a.toml,b.toml,c.toml

### PR DESCRIPTION
**Pull request by jgielstra**
Our team needs multiple configs for the same doc site to support different delivery channels.
We'd like to have a base config.toml and one or more child config.tomls overriding properties in the config.

I didn't see support for repeating command-line options in Cobra.  
I've added the ability pass multiple config files via `--config` as a comma delimited string.
For example: `hugo --config=base.toml,child1.toml,child2.toml`
Use viper's MergeConfig() to merge changes.

### CODE REVIEW

**Comment by bep** [comment]
3 things:

1) You need to hit the "sign CLA button"
2) How does this work with live-reloading?
3) This needs an test.

**Comment by jgielstra** [comment]
It seems I have done the CLA ??
If I click the CLA badge (https://cla-assistant.io/spf13/hugo?pullRequest=3532) I see..
"You have signed the CLA for spf13/hugo"

**Comment by bogem** [comment]
I don't see, what you signed the CLA too

**Comment by bep** [comment]
@jgielstra then I think there is a mismatch between your commit email and the email you have registered on your GitHub account. You can add multiple email addresses in your GH profile to handle this issue.

**Comment by jgielstra** [comment]
Thx that was indeed the case ..

**Comment by bep** [comment]
@jgielstra sorry about letting this drag out; it is maybe because of the move to a GitHub org, but the CLA still shows up as "not signed".

**Comment by jgielstra** [comment]
I have another work account..  I commited under that account to my personal github repo siiiigh. 
Please excuse the goose chase..

-Johan

**Comment by bep** [comment]
@spf13 @moorereason @digitalcraftsman and others: This seems like a great addition and I cannot think of a reason why this should bite us in the ass in the future?

**Comment by digitalcraftsman** [comment]
I like the idea of @jgielstra.

But I would like to turn the spotlight #3090 as well. It proposes to optionally externalize the site config into the data folder. This goes somewhere in the same direction.

In #3090 we literally split up a config file in smaller pieces. Using `hugo --config` would make it hard so say what files belong which configuration.

I just want to make sure we can incorporate both approaches.

**Comment by bep** [comment]
@jgielstra I have merged this, but it would also be nice to have a line or two in the documentation somewhere about this, and a PR for that (in this repo) would be welcomed.

**Comment by digitalcraftsman** [comment]
Is this feature still undocumented? If so we should open an issue for it.

**Comment by bep** [comment]
>Is this feature still undocumented? 

Yes. Lesson learned: Never merge PRs without doc.

**Comment by digitalcraftsman** [comment]
I've opened an issue as a reminder to document it.

https://github.com/gohugoio/hugoDocs/issues/146

**Pull request merged**
