### PR TITLE
docs: Show build time in last revision for autogenerated pages

### LINKED ISSUE #3497: docs: 404 page shows wrong "Last Revision"
Go to https://gohugo.io/what

Notice below:

Last revision: January 1, 0001

### PR DESCRIPTION
**Pull request by chankeypathak**
Fixes #3497

### CODE REVIEW

**Comment by chankeypathak** [comment]
I wonder what's causing the build to fail :|

**Comment by digitalcraftsman** [comment]
@chankeypathak this is not your fault. The build wasn't successful due to the deprecation of the `.Now` template func:

    ERROR 2017/05/23 08:20:25 Page's Now is deprecated and will be removed in Hugo 0.22. Use now (the template func).

So it's nothing related to this pr.

**Comment by digitalcraftsman** [comment]
@chankeypathak if you go to `http://localhost:1313/404.html` does the footer also show "Last revision: August 1, 2017"?

**Comment by chankeypathak** [comment]
@digitalcraftsman No. I see November 29, 2016. See the screenshot here: http://imgur.com/a/E9G60

**Comment by digitalcraftsman** [comment]
That's weird. I pulled the latest changes, used the latest version of Hugo and restarted the server to enforce a change. But I always get  "Last revision: August 1, 2017".

Could someone else test this out?

**Comment by digitalcraftsman** [comment]
The build time isn't part of the new design. Read #3497 for more information.

**Pull request closed without merging**
