### PR TITLE
Fix rebuild with resources.Concat

### LINKED ISSUE #12017: hugo server does not refresh page when using resources.Concat
I am convinced this is related to `resources.Concat`. The test case worked in v0.122.0. Git bisect says 7285e74090852b5d52f25e577850fa75f4aa8573 is the first "bad" commit, but that isn't terribly helpful.

#### Setup

```
assets/
└── a.css
```

layouts/partials/css.html

```
{{ $styles := slice }}
{{ range resources.Match "*.css" }}
  {{ $styles = $styles | append . }}
{{ end }}

{{ with resources.Concat "styles.css" $styles }}
  <link rel="stylesheet" href="{{ .RelPermalink }}">
{{ end }}
```

layouts/index.html

```text
<head>
  ...
  {{ partial "css.html" . }}
  ...
</head>
```

The test case only has one CSS file, but the number of files concatenated is irrelevant.

#### Example

```text
git clone --single-branch -b hugo-forum-topic-48181 https://github.com/jmooring/hugo-testing hugo-forum-topic-48181
cd hugo-forum-topic-48181
hugo server
```

Then modify assets/a.css while the server is running. The page does not refresh.

### PR DESCRIPTION
**Pull request by bep**
Fixes #12017

### CODE REVIEW

**Comment by jmooring** [comment]
This definitely fixes the test case I provided, but does not entirely fix the problem.

The [OP was unable to modify CSS](https://discourse.gohugo.io/t/48181) when using the popular PaperMod theme. I've created another test site, using the PaperMod theme, where it is easy to reproduce the problem.

```text
git clone --single-branch -b hugo-github-issue-12017 https://github.com/jmooring/hugo-testing hugo-github-issue-12017
cd hugo-github-issue-12017
hugo server
```

Then edit line 26 of themes/PaperMod/assets/css/common/header.css, changing the font size from 24px to 72px. The page does not reload as it did with v0.122.0.

**Comment by bep** [comment]
@jmooring OK, I will take another look at it, but it's important to understand that:

In `v0.123.0` we have shifted from a coarse grained to a fine grained rebuild setup. As part of that, we have removed most of the default Cache Buster config (most notably the setting that says that when resource with extension X (e.g. `.css`) changes, then invalidate all other resources with extension X) . But as in life in general, I give no guarantees, so the Cache Buster configuration is still relevant in some situations, and it's even more powerful than before, as it now triggers a rebuild of any resource/page that uses the "busted resource".

But, I will fix the `resources.Concat` func, I had forgotten about that one.

**Review by jmooring — COMMENTED** [review]
I tested with https://github.com/gohugoio/hugo/commit/163896873960f4a148663debb0c8d5e314547308 by doing...

```text
git clone --single-branch -b hugo-github-issue-12017 https://github.com/jmooring/hugo-testing hugo-github-issue-12017
cd hugo-github-issue-12017
hugo server
```

Then editing line 26 of themes/PaperMod/assets/css/common/header.css, changing the font size from 24px to 72px. The page does not reload as it did with v0.122.0... **until I save the file a second time (no changes to the file, just saving it again).**

Thinking this might be related to [12027](https://github.com/gohugoio/hugo/issues/12027) I ran `hugo server --renderToMemory`... this did not help.

**Comment by bep** [comment]
@jmooring consider this PR a work in progress at the moment. I have a little hard time wrapping my head around the PaperMod themes nesting of concats.

**Comment by jmooring** [comment]
> consider this PR a work in progress

Understood, I wasn't sure if the review request was new or left over from yesterday.

> I have a little hard time wrapping my head around the PaperMod themes nesting of concats

I'm glad it not just me.

**Comment by bep** [comment]
@jmooring the commit in 7fbe1b380f5eea7e17a9a548f621b3c4e6a6b937 fixes the PaperMod for me, but I need to understand ... why (and add a test for it) before I can close finish this. I wouldn't mind if you could take it for a spin and confirm/deny.

**Comment by jmooring** [comment]
> I wouldn't mind if you could take it for a spin and confirm/deny.

Tested at https://github.com/gohugoio/hugo/commit/403bcfb38725cbc35daa37d0143a698f8932cd13... works great!

**Comment by bep** [comment]
I have now applied a little bit cleaner fix for this. I'll admit it, I failed to create a breaking test case for this (kudos to the PaperMod folks!), but I looking at the current eviction construct, I guess it could pick up some odd corner cases.

**Pull request merged**
